/*
Copyright (c) 2015, Plume Design Inc. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
   1. Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
   3. Neither the name of the Plume Design Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL Plume Design Inc. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mdns_records_telemetry.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mdns_records_telemetry.pb-c.h"
void   interfaces__mdns_records_telemetry__mdns_record__init
                     (Interfaces__MdnsRecordsTelemetry__MdnsRecord         *message)
{
  static Interfaces__MdnsRecordsTelemetry__MdnsRecord init_value = INTERFACES__MDNS_RECORDS_TELEMETRY__MDNS_RECORD__INIT;
  *message = init_value;
}
size_t interfaces__mdns_records_telemetry__mdns_record__get_packed_size
                     (const Interfaces__MdnsRecordsTelemetry__MdnsRecord *message)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__mdns_record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t interfaces__mdns_records_telemetry__mdns_record__pack
                     (const Interfaces__MdnsRecordsTelemetry__MdnsRecord *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__mdns_record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t interfaces__mdns_records_telemetry__mdns_record__pack_to_buffer
                     (const Interfaces__MdnsRecordsTelemetry__MdnsRecord *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__mdns_record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Interfaces__MdnsRecordsTelemetry__MdnsRecord *
       interfaces__mdns_records_telemetry__mdns_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Interfaces__MdnsRecordsTelemetry__MdnsRecord *)
     protobuf_c_message_unpack (&interfaces__mdns_records_telemetry__mdns_record__descriptor,
                                allocator, len, data);
}
void   interfaces__mdns_records_telemetry__mdns_record__free_unpacked
                     (Interfaces__MdnsRecordsTelemetry__MdnsRecord *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__mdns_record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   interfaces__mdns_records_telemetry__mdns_client__init
                     (Interfaces__MdnsRecordsTelemetry__MdnsClient         *message)
{
  static Interfaces__MdnsRecordsTelemetry__MdnsClient init_value = INTERFACES__MDNS_RECORDS_TELEMETRY__MDNS_CLIENT__INIT;
  *message = init_value;
}
size_t interfaces__mdns_records_telemetry__mdns_client__get_packed_size
                     (const Interfaces__MdnsRecordsTelemetry__MdnsClient *message)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__mdns_client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t interfaces__mdns_records_telemetry__mdns_client__pack
                     (const Interfaces__MdnsRecordsTelemetry__MdnsClient *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__mdns_client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t interfaces__mdns_records_telemetry__mdns_client__pack_to_buffer
                     (const Interfaces__MdnsRecordsTelemetry__MdnsClient *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__mdns_client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Interfaces__MdnsRecordsTelemetry__MdnsClient *
       interfaces__mdns_records_telemetry__mdns_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Interfaces__MdnsRecordsTelemetry__MdnsClient *)
     protobuf_c_message_unpack (&interfaces__mdns_records_telemetry__mdns_client__descriptor,
                                allocator, len, data);
}
void   interfaces__mdns_records_telemetry__mdns_client__free_unpacked
                     (Interfaces__MdnsRecordsTelemetry__MdnsClient *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__mdns_client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   interfaces__mdns_records_telemetry__observation_point__init
                     (Interfaces__MdnsRecordsTelemetry__ObservationPoint         *message)
{
  static Interfaces__MdnsRecordsTelemetry__ObservationPoint init_value = INTERFACES__MDNS_RECORDS_TELEMETRY__OBSERVATION_POINT__INIT;
  *message = init_value;
}
size_t interfaces__mdns_records_telemetry__observation_point__get_packed_size
                     (const Interfaces__MdnsRecordsTelemetry__ObservationPoint *message)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__observation_point__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t interfaces__mdns_records_telemetry__observation_point__pack
                     (const Interfaces__MdnsRecordsTelemetry__ObservationPoint *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__observation_point__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t interfaces__mdns_records_telemetry__observation_point__pack_to_buffer
                     (const Interfaces__MdnsRecordsTelemetry__ObservationPoint *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__observation_point__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Interfaces__MdnsRecordsTelemetry__ObservationPoint *
       interfaces__mdns_records_telemetry__observation_point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Interfaces__MdnsRecordsTelemetry__ObservationPoint *)
     protobuf_c_message_unpack (&interfaces__mdns_records_telemetry__observation_point__descriptor,
                                allocator, len, data);
}
void   interfaces__mdns_records_telemetry__observation_point__free_unpacked
                     (Interfaces__MdnsRecordsTelemetry__ObservationPoint *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__observation_point__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   interfaces__mdns_records_telemetry__observation_window__init
                     (Interfaces__MdnsRecordsTelemetry__ObservationWindow         *message)
{
  static Interfaces__MdnsRecordsTelemetry__ObservationWindow init_value = INTERFACES__MDNS_RECORDS_TELEMETRY__OBSERVATION_WINDOW__INIT;
  *message = init_value;
}
size_t interfaces__mdns_records_telemetry__observation_window__get_packed_size
                     (const Interfaces__MdnsRecordsTelemetry__ObservationWindow *message)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__observation_window__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t interfaces__mdns_records_telemetry__observation_window__pack
                     (const Interfaces__MdnsRecordsTelemetry__ObservationWindow *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__observation_window__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t interfaces__mdns_records_telemetry__observation_window__pack_to_buffer
                     (const Interfaces__MdnsRecordsTelemetry__ObservationWindow *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__observation_window__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Interfaces__MdnsRecordsTelemetry__ObservationWindow *
       interfaces__mdns_records_telemetry__observation_window__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Interfaces__MdnsRecordsTelemetry__ObservationWindow *)
     protobuf_c_message_unpack (&interfaces__mdns_records_telemetry__observation_window__descriptor,
                                allocator, len, data);
}
void   interfaces__mdns_records_telemetry__observation_window__free_unpacked
                     (Interfaces__MdnsRecordsTelemetry__ObservationWindow *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__observation_window__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   interfaces__mdns_records_telemetry__mdns_records_report__init
                     (Interfaces__MdnsRecordsTelemetry__MdnsRecordsReport         *message)
{
  static Interfaces__MdnsRecordsTelemetry__MdnsRecordsReport init_value = INTERFACES__MDNS_RECORDS_TELEMETRY__MDNS_RECORDS_REPORT__INIT;
  *message = init_value;
}
size_t interfaces__mdns_records_telemetry__mdns_records_report__get_packed_size
                     (const Interfaces__MdnsRecordsTelemetry__MdnsRecordsReport *message)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__mdns_records_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t interfaces__mdns_records_telemetry__mdns_records_report__pack
                     (const Interfaces__MdnsRecordsTelemetry__MdnsRecordsReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__mdns_records_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t interfaces__mdns_records_telemetry__mdns_records_report__pack_to_buffer
                     (const Interfaces__MdnsRecordsTelemetry__MdnsRecordsReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__mdns_records_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Interfaces__MdnsRecordsTelemetry__MdnsRecordsReport *
       interfaces__mdns_records_telemetry__mdns_records_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Interfaces__MdnsRecordsTelemetry__MdnsRecordsReport *)
     protobuf_c_message_unpack (&interfaces__mdns_records_telemetry__mdns_records_report__descriptor,
                                allocator, len, data);
}
void   interfaces__mdns_records_telemetry__mdns_records_report__free_unpacked
                     (Interfaces__MdnsRecordsTelemetry__MdnsRecordsReport *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &interfaces__mdns_records_telemetry__mdns_records_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor interfaces__mdns_records_telemetry__mdns_record__field_descriptors[8] =
{
  {
    "owner_name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecord, owner_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecord, has_type),
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecord, type),
    &interfaces__mdns_records_telemetry__mdns_record_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "domain_name",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecord, domain_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecord, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "res_desc",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecord, has_res_desc),
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecord, res_desc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "priority",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecord, has_priority),
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecord, priority),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "weight",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecord, has_weight),
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecord, weight),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecord, has_port),
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecord, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned interfaces__mdns_records_telemetry__mdns_record__field_indices_by_name[] = {
  2,   /* field[2] = domain_name */
  3,   /* field[3] = ip */
  0,   /* field[0] = owner_name */
  7,   /* field[7] = port */
  5,   /* field[5] = priority */
  4,   /* field[4] = res_desc */
  1,   /* field[1] = type */
  6,   /* field[6] = weight */
};
static const ProtobufCIntRange interfaces__mdns_records_telemetry__mdns_record__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor interfaces__mdns_records_telemetry__mdns_record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "interfaces.mdns_records_telemetry.MdnsRecord",
  "MdnsRecord",
  "Interfaces__MdnsRecordsTelemetry__MdnsRecord",
  "interfaces.mdns_records_telemetry",
  sizeof(Interfaces__MdnsRecordsTelemetry__MdnsRecord),
  8,
  interfaces__mdns_records_telemetry__mdns_record__field_descriptors,
  interfaces__mdns_records_telemetry__mdns_record__field_indices_by_name,
  1,  interfaces__mdns_records_telemetry__mdns_record__number_ranges,
  (ProtobufCMessageInit) interfaces__mdns_records_telemetry__mdns_record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor interfaces__mdns_records_telemetry__mdns_client__field_descriptors[3] =
{
  {
    "mac",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsClient, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsClient, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mdns_records",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsClient, n_mdns_records),
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsClient, mdns_records),
    &interfaces__mdns_records_telemetry__mdns_record__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned interfaces__mdns_records_telemetry__mdns_client__field_indices_by_name[] = {
  1,   /* field[1] = ip */
  0,   /* field[0] = mac */
  2,   /* field[2] = mdns_records */
};
static const ProtobufCIntRange interfaces__mdns_records_telemetry__mdns_client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor interfaces__mdns_records_telemetry__mdns_client__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "interfaces.mdns_records_telemetry.MdnsClient",
  "MdnsClient",
  "Interfaces__MdnsRecordsTelemetry__MdnsClient",
  "interfaces.mdns_records_telemetry",
  sizeof(Interfaces__MdnsRecordsTelemetry__MdnsClient),
  3,
  interfaces__mdns_records_telemetry__mdns_client__field_descriptors,
  interfaces__mdns_records_telemetry__mdns_client__field_indices_by_name,
  1,  interfaces__mdns_records_telemetry__mdns_client__number_ranges,
  (ProtobufCMessageInit) interfaces__mdns_records_telemetry__mdns_client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor interfaces__mdns_records_telemetry__observation_point__field_descriptors[2] =
{
  {
    "node_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__MdnsRecordsTelemetry__ObservationPoint, node_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__MdnsRecordsTelemetry__ObservationPoint, location_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned interfaces__mdns_records_telemetry__observation_point__field_indices_by_name[] = {
  1,   /* field[1] = location_id */
  0,   /* field[0] = node_id */
};
static const ProtobufCIntRange interfaces__mdns_records_telemetry__observation_point__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor interfaces__mdns_records_telemetry__observation_point__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "interfaces.mdns_records_telemetry.ObservationPoint",
  "ObservationPoint",
  "Interfaces__MdnsRecordsTelemetry__ObservationPoint",
  "interfaces.mdns_records_telemetry",
  sizeof(Interfaces__MdnsRecordsTelemetry__ObservationPoint),
  2,
  interfaces__mdns_records_telemetry__observation_point__field_descriptors,
  interfaces__mdns_records_telemetry__observation_point__field_indices_by_name,
  1,  interfaces__mdns_records_telemetry__observation_point__number_ranges,
  (ProtobufCMessageInit) interfaces__mdns_records_telemetry__observation_point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor interfaces__mdns_records_telemetry__observation_window__field_descriptors[2] =
{
  {
    "started_at",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Interfaces__MdnsRecordsTelemetry__ObservationWindow, has_started_at),
    offsetof(Interfaces__MdnsRecordsTelemetry__ObservationWindow, started_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ended_at",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Interfaces__MdnsRecordsTelemetry__ObservationWindow, has_ended_at),
    offsetof(Interfaces__MdnsRecordsTelemetry__ObservationWindow, ended_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned interfaces__mdns_records_telemetry__observation_window__field_indices_by_name[] = {
  1,   /* field[1] = ended_at */
  0,   /* field[0] = started_at */
};
static const ProtobufCIntRange interfaces__mdns_records_telemetry__observation_window__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor interfaces__mdns_records_telemetry__observation_window__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "interfaces.mdns_records_telemetry.ObservationWindow",
  "ObservationWindow",
  "Interfaces__MdnsRecordsTelemetry__ObservationWindow",
  "interfaces.mdns_records_telemetry",
  sizeof(Interfaces__MdnsRecordsTelemetry__ObservationWindow),
  2,
  interfaces__mdns_records_telemetry__observation_window__field_descriptors,
  interfaces__mdns_records_telemetry__observation_window__field_indices_by_name,
  1,  interfaces__mdns_records_telemetry__observation_window__number_ranges,
  (ProtobufCMessageInit) interfaces__mdns_records_telemetry__observation_window__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor interfaces__mdns_records_telemetry__mdns_records_report__field_descriptors[3] =
{
  {
    "observation_point",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecordsReport, observation_point),
    &interfaces__mdns_records_telemetry__observation_point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "observation_window",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecordsReport, observation_window),
    &interfaces__mdns_records_telemetry__observation_window__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clients",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecordsReport, n_clients),
    offsetof(Interfaces__MdnsRecordsTelemetry__MdnsRecordsReport, clients),
    &interfaces__mdns_records_telemetry__mdns_client__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned interfaces__mdns_records_telemetry__mdns_records_report__field_indices_by_name[] = {
  2,   /* field[2] = clients */
  0,   /* field[0] = observation_point */
  1,   /* field[1] = observation_window */
};
static const ProtobufCIntRange interfaces__mdns_records_telemetry__mdns_records_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor interfaces__mdns_records_telemetry__mdns_records_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "interfaces.mdns_records_telemetry.MdnsRecordsReport",
  "MdnsRecordsReport",
  "Interfaces__MdnsRecordsTelemetry__MdnsRecordsReport",
  "interfaces.mdns_records_telemetry",
  sizeof(Interfaces__MdnsRecordsTelemetry__MdnsRecordsReport),
  3,
  interfaces__mdns_records_telemetry__mdns_records_report__field_descriptors,
  interfaces__mdns_records_telemetry__mdns_records_report__field_indices_by_name,
  1,  interfaces__mdns_records_telemetry__mdns_records_report__number_ranges,
  (ProtobufCMessageInit) interfaces__mdns_records_telemetry__mdns_records_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue interfaces__mdns_records_telemetry__mdns_record_type__enum_values_by_number[7] =
{
  { "MDNS_RECORD_TYPE_UNSPECIFIED", "INTERFACES__MDNS_RECORDS_TELEMETRY__MDNS_RECORD_TYPE__MDNS_RECORD_TYPE_UNSPECIFIED", 0 },
  { "MDNS_RECORD_TYPE_A", "INTERFACES__MDNS_RECORDS_TELEMETRY__MDNS_RECORD_TYPE__MDNS_RECORD_TYPE_A", 1 },
  { "MDNS_RECORD_TYPE_NS", "INTERFACES__MDNS_RECORDS_TELEMETRY__MDNS_RECORD_TYPE__MDNS_RECORD_TYPE_NS", 2 },
  { "MDNS_RECORD_TYPE_CNAME", "INTERFACES__MDNS_RECORDS_TELEMETRY__MDNS_RECORD_TYPE__MDNS_RECORD_TYPE_CNAME", 3 },
  { "MDNS_RECORD_TYPE_PTR", "INTERFACES__MDNS_RECORDS_TELEMETRY__MDNS_RECORD_TYPE__MDNS_RECORD_TYPE_PTR", 4 },
  { "MDNS_RECORD_TYPE_TXT", "INTERFACES__MDNS_RECORDS_TELEMETRY__MDNS_RECORD_TYPE__MDNS_RECORD_TYPE_TXT", 5 },
  { "MDNS_RECORD_TYPE_SRV", "INTERFACES__MDNS_RECORDS_TELEMETRY__MDNS_RECORD_TYPE__MDNS_RECORD_TYPE_SRV", 6 },
};
static const ProtobufCIntRange interfaces__mdns_records_telemetry__mdns_record_type__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex interfaces__mdns_records_telemetry__mdns_record_type__enum_values_by_name[7] =
{
  { "MDNS_RECORD_TYPE_A", 1 },
  { "MDNS_RECORD_TYPE_CNAME", 3 },
  { "MDNS_RECORD_TYPE_NS", 2 },
  { "MDNS_RECORD_TYPE_PTR", 4 },
  { "MDNS_RECORD_TYPE_SRV", 6 },
  { "MDNS_RECORD_TYPE_TXT", 5 },
  { "MDNS_RECORD_TYPE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor interfaces__mdns_records_telemetry__mdns_record_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "interfaces.mdns_records_telemetry.MdnsRecordType",
  "MdnsRecordType",
  "Interfaces__MdnsRecordsTelemetry__MdnsRecordType",
  "interfaces.mdns_records_telemetry",
  7,
  interfaces__mdns_records_telemetry__mdns_record_type__enum_values_by_number,
  7,
  interfaces__mdns_records_telemetry__mdns_record_type__enum_values_by_name,
  1,
  interfaces__mdns_records_telemetry__mdns_record_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
