#!/bin/sh

ref_btm_req=$(cat <<-.
	BTM_REQUEST
	mac=20:00:00:00:00:00
	ifname=wlan0
	neighs=
	    bssid=DE:AF:CA:FE:FE:ED
	    bssid_info=143
	    op_class=115
	    phy_type=9
	    opt_subelems=
	    opt_subelems_len=0
	
	    bssid=DE:AD:BE:EF:FE:ED
	    bssid_info=143
	    op_class=115
	    phy_type=9
	    opt_subelems=
	    opt_subelems_len=0
	
	    bssid=10:00:00:00:00:01
	    bssid_info=143
	    op_class=115
	    phy_type=9
	    opt_subelems=
	    opt_subelems_len=0
	
	num_neigh=3
	valid_int=255
	abridged=1
	pref=1
	disassoc_imminent=0
	bss_term=0
	tries=2
	max_tries=1
	retry_interval=1
	inc_neigh=true
	inc_self=true
.
)

