#!/bin/sh -axe
#
# This is intended to be run from (the same as native target
# was built in) docker instance, from the opensync root
# directory (the one, where core/, platform/ and vendor/
# directories are at).
#

self=$(readlink -f "$0")
init=$self.init
bm=$(readlink -f core/work/bsal_sim-*/bin/bm)
db=$(readlink -f core/work/bsal_sim-*/rootfs/usr/opensync/etc/conf.db.bck)
ovsh=$(readlink -f core/work/bsal_sim-*/bin/ovsh)
mem=${mem:-128M}
dir=$(dirname "$self")

# FIXME: This could be run in parallel
for i in "$@"
do
	mkdir -p "$dir/logs/$i"
	linux.uml \
		mem=$mem \
		time-travel=inf-cpu \
		hostfs=/ \
		root=none \
		rootfstype=hostfs \
		mac80211_hwsim.radios=7 \
		rootflags=/ \
		init=$init \
		env=$(env | grep opt_ | base64 -w0) \
		env_dir=$dir \
		env_db=$db \
		env_bm=$bm \
		env_cmd="./$i" \
		 2>&1 | tee "$dir/logs/$i/log"
done
