/*
Copyright (c) 2015, Plume Design Inc. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
   1. Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
   3. Neither the name of the Plume Design Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL Plume Design Inc. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: network_metadata.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "network_metadata.pb-c.h"
void   traffic__observation_point__init
                     (Traffic__ObservationPoint         *message)
{
  static Traffic__ObservationPoint init_value = TRAFFIC__OBSERVATION_POINT__INIT;
  *message = init_value;
}
size_t traffic__observation_point__get_packed_size
                     (const Traffic__ObservationPoint *message)
{
  assert(message->base.descriptor == &traffic__observation_point__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t traffic__observation_point__pack
                     (const Traffic__ObservationPoint *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &traffic__observation_point__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t traffic__observation_point__pack_to_buffer
                     (const Traffic__ObservationPoint *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &traffic__observation_point__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Traffic__ObservationPoint *
       traffic__observation_point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Traffic__ObservationPoint *)
     protobuf_c_message_unpack (&traffic__observation_point__descriptor,
                                allocator, len, data);
}
void   traffic__observation_point__free_unpacked
                     (Traffic__ObservationPoint *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &traffic__observation_point__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   traffic__vendor_data__kvpair__init
                     (Traffic__VendorDataKVPair         *message)
{
  static Traffic__VendorDataKVPair init_value = TRAFFIC__VENDOR_DATA__KVPAIR__INIT;
  *message = init_value;
}
size_t traffic__vendor_data__kvpair__get_packed_size
                     (const Traffic__VendorDataKVPair *message)
{
  assert(message->base.descriptor == &traffic__vendor_data__kvpair__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t traffic__vendor_data__kvpair__pack
                     (const Traffic__VendorDataKVPair *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &traffic__vendor_data__kvpair__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t traffic__vendor_data__kvpair__pack_to_buffer
                     (const Traffic__VendorDataKVPair *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &traffic__vendor_data__kvpair__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Traffic__VendorDataKVPair *
       traffic__vendor_data__kvpair__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Traffic__VendorDataKVPair *)
     protobuf_c_message_unpack (&traffic__vendor_data__kvpair__descriptor,
                                allocator, len, data);
}
void   traffic__vendor_data__kvpair__free_unpacked
                     (Traffic__VendorDataKVPair *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &traffic__vendor_data__kvpair__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   traffic__vendor_data__init
                     (Traffic__VendorData         *message)
{
  static Traffic__VendorData init_value = TRAFFIC__VENDOR_DATA__INIT;
  *message = init_value;
}
size_t traffic__vendor_data__get_packed_size
                     (const Traffic__VendorData *message)
{
  assert(message->base.descriptor == &traffic__vendor_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t traffic__vendor_data__pack
                     (const Traffic__VendorData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &traffic__vendor_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t traffic__vendor_data__pack_to_buffer
                     (const Traffic__VendorData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &traffic__vendor_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Traffic__VendorData *
       traffic__vendor_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Traffic__VendorData *)
     protobuf_c_message_unpack (&traffic__vendor_data__descriptor,
                                allocator, len, data);
}
void   traffic__vendor_data__free_unpacked
                     (Traffic__VendorData *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &traffic__vendor_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   traffic__flow_tags__init
                     (Traffic__FlowTags         *message)
{
  static Traffic__FlowTags init_value = TRAFFIC__FLOW_TAGS__INIT;
  *message = init_value;
}
size_t traffic__flow_tags__get_packed_size
                     (const Traffic__FlowTags *message)
{
  assert(message->base.descriptor == &traffic__flow_tags__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t traffic__flow_tags__pack
                     (const Traffic__FlowTags *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &traffic__flow_tags__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t traffic__flow_tags__pack_to_buffer
                     (const Traffic__FlowTags *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &traffic__flow_tags__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Traffic__FlowTags *
       traffic__flow_tags__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Traffic__FlowTags *)
     protobuf_c_message_unpack (&traffic__flow_tags__descriptor,
                                allocator, len, data);
}
void   traffic__flow_tags__free_unpacked
                     (Traffic__FlowTags *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &traffic__flow_tags__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   traffic__flow_state__init
                     (Traffic__FlowState         *message)
{
  static Traffic__FlowState init_value = TRAFFIC__FLOW_STATE__INIT;
  *message = init_value;
}
size_t traffic__flow_state__get_packed_size
                     (const Traffic__FlowState *message)
{
  assert(message->base.descriptor == &traffic__flow_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t traffic__flow_state__pack
                     (const Traffic__FlowState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &traffic__flow_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t traffic__flow_state__pack_to_buffer
                     (const Traffic__FlowState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &traffic__flow_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Traffic__FlowState *
       traffic__flow_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Traffic__FlowState *)
     protobuf_c_message_unpack (&traffic__flow_state__descriptor,
                                allocator, len, data);
}
void   traffic__flow_state__free_unpacked
                     (Traffic__FlowState *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &traffic__flow_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   traffic__flow_key__init
                     (Traffic__FlowKey         *message)
{
  static Traffic__FlowKey init_value = TRAFFIC__FLOW_KEY__INIT;
  *message = init_value;
}
size_t traffic__flow_key__get_packed_size
                     (const Traffic__FlowKey *message)
{
  assert(message->base.descriptor == &traffic__flow_key__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t traffic__flow_key__pack
                     (const Traffic__FlowKey *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &traffic__flow_key__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t traffic__flow_key__pack_to_buffer
                     (const Traffic__FlowKey *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &traffic__flow_key__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Traffic__FlowKey *
       traffic__flow_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Traffic__FlowKey *)
     protobuf_c_message_unpack (&traffic__flow_key__descriptor,
                                allocator, len, data);
}
void   traffic__flow_key__free_unpacked
                     (Traffic__FlowKey *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &traffic__flow_key__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   traffic__flow_counters__init
                     (Traffic__FlowCounters         *message)
{
  static Traffic__FlowCounters init_value = TRAFFIC__FLOW_COUNTERS__INIT;
  *message = init_value;
}
size_t traffic__flow_counters__get_packed_size
                     (const Traffic__FlowCounters *message)
{
  assert(message->base.descriptor == &traffic__flow_counters__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t traffic__flow_counters__pack
                     (const Traffic__FlowCounters *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &traffic__flow_counters__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t traffic__flow_counters__pack_to_buffer
                     (const Traffic__FlowCounters *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &traffic__flow_counters__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Traffic__FlowCounters *
       traffic__flow_counters__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Traffic__FlowCounters *)
     protobuf_c_message_unpack (&traffic__flow_counters__descriptor,
                                allocator, len, data);
}
void   traffic__flow_counters__free_unpacked
                     (Traffic__FlowCounters *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &traffic__flow_counters__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   traffic__flow_stats__init
                     (Traffic__FlowStats         *message)
{
  static Traffic__FlowStats init_value = TRAFFIC__FLOW_STATS__INIT;
  *message = init_value;
}
size_t traffic__flow_stats__get_packed_size
                     (const Traffic__FlowStats *message)
{
  assert(message->base.descriptor == &traffic__flow_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t traffic__flow_stats__pack
                     (const Traffic__FlowStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &traffic__flow_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t traffic__flow_stats__pack_to_buffer
                     (const Traffic__FlowStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &traffic__flow_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Traffic__FlowStats *
       traffic__flow_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Traffic__FlowStats *)
     protobuf_c_message_unpack (&traffic__flow_stats__descriptor,
                                allocator, len, data);
}
void   traffic__flow_stats__free_unpacked
                     (Traffic__FlowStats *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &traffic__flow_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   traffic__observation_window__init
                     (Traffic__ObservationWindow         *message)
{
  static Traffic__ObservationWindow init_value = TRAFFIC__OBSERVATION_WINDOW__INIT;
  *message = init_value;
}
size_t traffic__observation_window__get_packed_size
                     (const Traffic__ObservationWindow *message)
{
  assert(message->base.descriptor == &traffic__observation_window__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t traffic__observation_window__pack
                     (const Traffic__ObservationWindow *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &traffic__observation_window__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t traffic__observation_window__pack_to_buffer
                     (const Traffic__ObservationWindow *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &traffic__observation_window__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Traffic__ObservationWindow *
       traffic__observation_window__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Traffic__ObservationWindow *)
     protobuf_c_message_unpack (&traffic__observation_window__descriptor,
                                allocator, len, data);
}
void   traffic__observation_window__free_unpacked
                     (Traffic__ObservationWindow *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &traffic__observation_window__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   traffic__flow_report__init
                     (Traffic__FlowReport         *message)
{
  static Traffic__FlowReport init_value = TRAFFIC__FLOW_REPORT__INIT;
  *message = init_value;
}
size_t traffic__flow_report__get_packed_size
                     (const Traffic__FlowReport *message)
{
  assert(message->base.descriptor == &traffic__flow_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t traffic__flow_report__pack
                     (const Traffic__FlowReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &traffic__flow_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t traffic__flow_report__pack_to_buffer
                     (const Traffic__FlowReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &traffic__flow_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Traffic__FlowReport *
       traffic__flow_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Traffic__FlowReport *)
     protobuf_c_message_unpack (&traffic__flow_report__descriptor,
                                allocator, len, data);
}
void   traffic__flow_report__free_unpacked
                     (Traffic__FlowReport *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &traffic__flow_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor traffic__observation_point__field_descriptors[2] =
{
  {
    "nodeId",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Traffic__ObservationPoint, nodeid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "locationId",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Traffic__ObservationPoint, locationid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned traffic__observation_point__field_indices_by_name[] = {
  1,   /* field[1] = locationId */
  0,   /* field[0] = nodeId */
};
static const ProtobufCIntRange traffic__observation_point__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor traffic__observation_point__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "traffic.ObservationPoint",
  "ObservationPoint",
  "Traffic__ObservationPoint",
  "traffic",
  sizeof(Traffic__ObservationPoint),
  2,
  traffic__observation_point__field_descriptors,
  traffic__observation_point__field_indices_by_name,
  1,  traffic__observation_point__number_ranges,
  (ProtobufCMessageInit) traffic__observation_point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor traffic__vendor_data__kvpair__field_descriptors[4] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Traffic__VendorDataKVPair, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "val_str",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Traffic__VendorDataKVPair, val_str),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "val_u32",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Traffic__VendorDataKVPair, has_val_u32),
    offsetof(Traffic__VendorDataKVPair, val_u32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "val_u64",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Traffic__VendorDataKVPair, has_val_u64),
    offsetof(Traffic__VendorDataKVPair, val_u64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned traffic__vendor_data__kvpair__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = val_str */
  2,   /* field[2] = val_u32 */
  3,   /* field[3] = val_u64 */
};
static const ProtobufCIntRange traffic__vendor_data__kvpair__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor traffic__vendor_data__kvpair__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "traffic.VendorData_KVPair",
  "VendorDataKVPair",
  "Traffic__VendorDataKVPair",
  "traffic",
  sizeof(Traffic__VendorDataKVPair),
  4,
  traffic__vendor_data__kvpair__field_descriptors,
  traffic__vendor_data__kvpair__field_indices_by_name,
  1,  traffic__vendor_data__kvpair__number_ranges,
  (ProtobufCMessageInit) traffic__vendor_data__kvpair__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor traffic__vendor_data__field_descriptors[2] =
{
  {
    "vendor",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Traffic__VendorData, vendor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendorKVPair",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Traffic__VendorData, n_vendorkvpair),
    offsetof(Traffic__VendorData, vendorkvpair),
    &traffic__vendor_data__kvpair__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned traffic__vendor_data__field_indices_by_name[] = {
  0,   /* field[0] = vendor */
  1,   /* field[1] = vendorKVPair */
};
static const ProtobufCIntRange traffic__vendor_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor traffic__vendor_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "traffic.VendorData",
  "VendorData",
  "Traffic__VendorData",
  "traffic",
  sizeof(Traffic__VendorData),
  2,
  traffic__vendor_data__field_descriptors,
  traffic__vendor_data__field_indices_by_name,
  1,  traffic__vendor_data__number_ranges,
  (ProtobufCMessageInit) traffic__vendor_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor traffic__flow_tags__field_descriptors[3] =
{
  {
    "vendor",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Traffic__FlowTags, vendor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "appName",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Traffic__FlowTags, appname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "appTags",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Traffic__FlowTags, n_apptags),
    offsetof(Traffic__FlowTags, apptags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned traffic__flow_tags__field_indices_by_name[] = {
  1,   /* field[1] = appName */
  2,   /* field[2] = appTags */
  0,   /* field[0] = vendor */
};
static const ProtobufCIntRange traffic__flow_tags__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor traffic__flow_tags__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "traffic.FlowTags",
  "FlowTags",
  "Traffic__FlowTags",
  "traffic",
  sizeof(Traffic__FlowTags),
  3,
  traffic__flow_tags__field_descriptors,
  traffic__flow_tags__field_indices_by_name,
  2,  traffic__flow_tags__number_ranges,
  (ProtobufCMessageInit) traffic__flow_tags__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor traffic__flow_state__field_descriptors[4] =
{
  {
    "firstObservedAt",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Traffic__FlowState, has_firstobservedat),
    offsetof(Traffic__FlowState, firstobservedat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lastObservedAt",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Traffic__FlowState, has_lastobservedat),
    offsetof(Traffic__FlowState, lastobservedat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flowStart",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Traffic__FlowState, has_flowstart),
    offsetof(Traffic__FlowState, flowstart),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flowEnd",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Traffic__FlowState, has_flowend),
    offsetof(Traffic__FlowState, flowend),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned traffic__flow_state__field_indices_by_name[] = {
  0,   /* field[0] = firstObservedAt */
  3,   /* field[3] = flowEnd */
  2,   /* field[2] = flowStart */
  1,   /* field[1] = lastObservedAt */
};
static const ProtobufCIntRange traffic__flow_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor traffic__flow_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "traffic.FlowState",
  "FlowState",
  "Traffic__FlowState",
  "traffic",
  sizeof(Traffic__FlowState),
  4,
  traffic__flow_state__field_descriptors,
  traffic__flow_state__field_indices_by_name,
  1,  traffic__flow_state__number_ranges,
  (ProtobufCMessageInit) traffic__flow_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor traffic__flow_key__field_descriptors[14] =
{
  {
    "srcMac",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Traffic__FlowKey, srcmac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dstMac",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Traffic__FlowKey, dstmac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vlanId",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Traffic__FlowKey, has_vlanid),
    offsetof(Traffic__FlowKey, vlanid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "etherType",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Traffic__FlowKey, has_ethertype),
    offsetof(Traffic__FlowKey, ethertype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "srcIp",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Traffic__FlowKey, srcip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dstIp",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Traffic__FlowKey, dstip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipProtocol",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Traffic__FlowKey, has_ipprotocol),
    offsetof(Traffic__FlowKey, ipprotocol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tptSrcPort",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Traffic__FlowKey, has_tptsrcport),
    offsetof(Traffic__FlowKey, tptsrcport),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tptDstPort",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Traffic__FlowKey, has_tptdstport),
    offsetof(Traffic__FlowKey, tptdstport),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flowTags",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Traffic__FlowKey, n_flowtags),
    offsetof(Traffic__FlowKey, flowtags),
    &traffic__flow_tags__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendorData",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Traffic__FlowKey, n_vendordata),
    offsetof(Traffic__FlowKey, vendordata),
    &traffic__vendor_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flowState",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Traffic__FlowKey, flowstate),
    &traffic__flow_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parentOfSrcMac",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Traffic__FlowKey, has_parentofsrcmac),
    offsetof(Traffic__FlowKey, parentofsrcmac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parentOfDstMac",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Traffic__FlowKey, has_parentofdstmac),
    offsetof(Traffic__FlowKey, parentofdstmac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned traffic__flow_key__field_indices_by_name[] = {
  5,   /* field[5] = dstIp */
  1,   /* field[1] = dstMac */
  3,   /* field[3] = etherType */
  11,   /* field[11] = flowState */
  9,   /* field[9] = flowTags */
  6,   /* field[6] = ipProtocol */
  13,   /* field[13] = parentOfDstMac */
  12,   /* field[12] = parentOfSrcMac */
  4,   /* field[4] = srcIp */
  0,   /* field[0] = srcMac */
  8,   /* field[8] = tptDstPort */
  7,   /* field[7] = tptSrcPort */
  10,   /* field[10] = vendorData */
  2,   /* field[2] = vlanId */
};
static const ProtobufCIntRange traffic__flow_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor traffic__flow_key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "traffic.FlowKey",
  "FlowKey",
  "Traffic__FlowKey",
  "traffic",
  sizeof(Traffic__FlowKey),
  14,
  traffic__flow_key__field_descriptors,
  traffic__flow_key__field_indices_by_name,
  1,  traffic__flow_key__number_ranges,
  (ProtobufCMessageInit) traffic__flow_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor traffic__flow_counters__field_descriptors[2] =
{
  {
    "packetsCount",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Traffic__FlowCounters, has_packetscount),
    offsetof(Traffic__FlowCounters, packetscount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytesCount",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Traffic__FlowCounters, has_bytescount),
    offsetof(Traffic__FlowCounters, bytescount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned traffic__flow_counters__field_indices_by_name[] = {
  1,   /* field[1] = bytesCount */
  0,   /* field[0] = packetsCount */
};
static const ProtobufCIntRange traffic__flow_counters__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor traffic__flow_counters__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "traffic.FlowCounters",
  "FlowCounters",
  "Traffic__FlowCounters",
  "traffic",
  sizeof(Traffic__FlowCounters),
  2,
  traffic__flow_counters__field_descriptors,
  traffic__flow_counters__field_indices_by_name,
  1,  traffic__flow_counters__number_ranges,
  (ProtobufCMessageInit) traffic__flow_counters__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor traffic__flow_stats__field_descriptors[2] =
{
  {
    "flowKey",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Traffic__FlowStats, flowkey),
    &traffic__flow_key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flowCount",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Traffic__FlowStats, flowcount),
    &traffic__flow_counters__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned traffic__flow_stats__field_indices_by_name[] = {
  1,   /* field[1] = flowCount */
  0,   /* field[0] = flowKey */
};
static const ProtobufCIntRange traffic__flow_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor traffic__flow_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "traffic.FlowStats",
  "FlowStats",
  "Traffic__FlowStats",
  "traffic",
  sizeof(Traffic__FlowStats),
  2,
  traffic__flow_stats__field_descriptors,
  traffic__flow_stats__field_indices_by_name,
  1,  traffic__flow_stats__number_ranges,
  (ProtobufCMessageInit) traffic__flow_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor traffic__observation_window__field_descriptors[4] =
{
  {
    "startedAt",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Traffic__ObservationWindow, has_startedat),
    offsetof(Traffic__ObservationWindow, startedat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "endedAt",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Traffic__ObservationWindow, has_endedat),
    offsetof(Traffic__ObservationWindow, endedat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flowStats",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Traffic__ObservationWindow, n_flowstats),
    offsetof(Traffic__ObservationWindow, flowstats),
    &traffic__flow_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "droppedFlows",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Traffic__ObservationWindow, has_droppedflows),
    offsetof(Traffic__ObservationWindow, droppedflows),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned traffic__observation_window__field_indices_by_name[] = {
  3,   /* field[3] = droppedFlows */
  1,   /* field[1] = endedAt */
  2,   /* field[2] = flowStats */
  0,   /* field[0] = startedAt */
};
static const ProtobufCIntRange traffic__observation_window__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor traffic__observation_window__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "traffic.ObservationWindow",
  "ObservationWindow",
  "Traffic__ObservationWindow",
  "traffic",
  sizeof(Traffic__ObservationWindow),
  4,
  traffic__observation_window__field_descriptors,
  traffic__observation_window__field_indices_by_name,
  1,  traffic__observation_window__number_ranges,
  (ProtobufCMessageInit) traffic__observation_window__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor traffic__flow_report__field_descriptors[3] =
{
  {
    "reportedAt",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Traffic__FlowReport, has_reportedat),
    offsetof(Traffic__FlowReport, reportedat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "observationPoint",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Traffic__FlowReport, observationpoint),
    &traffic__observation_point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "observationWindow",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Traffic__FlowReport, n_observationwindow),
    offsetof(Traffic__FlowReport, observationwindow),
    &traffic__observation_window__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned traffic__flow_report__field_indices_by_name[] = {
  1,   /* field[1] = observationPoint */
  2,   /* field[2] = observationWindow */
  0,   /* field[0] = reportedAt */
};
static const ProtobufCIntRange traffic__flow_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor traffic__flow_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "traffic.FlowReport",
  "FlowReport",
  "Traffic__FlowReport",
  "traffic",
  sizeof(Traffic__FlowReport),
  3,
  traffic__flow_report__field_descriptors,
  traffic__flow_report__field_indices_by_name,
  1,  traffic__flow_report__number_ranges,
  (ProtobufCMessageInit) traffic__flow_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
