/*
Copyright (c) 2015, Plume Design Inc. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
   1. Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
   3. Neither the name of the Plume Design Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL Plume Design Inc. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: time_event.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "time_event.pb-c.h"
void   sts__time_event__init
                     (Sts__TimeEvent         *message)
{
  static const Sts__TimeEvent init_value = STS__TIME_EVENT__INIT;
  *message = init_value;
}
size_t sts__time_event__get_packed_size
                     (const Sts__TimeEvent *message)
{
  assert(message->base.descriptor == &sts__time_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sts__time_event__pack
                     (const Sts__TimeEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sts__time_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sts__time_event__pack_to_buffer
                     (const Sts__TimeEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sts__time_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sts__TimeEvent *
       sts__time_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sts__TimeEvent *)
     protobuf_c_message_unpack (&sts__time_event__descriptor,
                                allocator, len, data);
}
void   sts__time_event__free_unpacked
                     (Sts__TimeEvent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sts__time_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sts__device_id__init
                     (Sts__DeviceID         *message)
{
  static const Sts__DeviceID init_value = STS__DEVICE_ID__INIT;
  *message = init_value;
}
size_t sts__device_id__get_packed_size
                     (const Sts__DeviceID *message)
{
  assert(message->base.descriptor == &sts__device_id__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sts__device_id__pack
                     (const Sts__DeviceID *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sts__device_id__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sts__device_id__pack_to_buffer
                     (const Sts__DeviceID *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sts__device_id__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sts__DeviceID *
       sts__device_id__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sts__DeviceID *)
     protobuf_c_message_unpack (&sts__device_id__descriptor,
                                allocator, len, data);
}
void   sts__device_id__free_unpacked
                     (Sts__DeviceID *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sts__device_id__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sts__time_events_report__init
                     (Sts__TimeEventsReport         *message)
{
  static const Sts__TimeEventsReport init_value = STS__TIME_EVENTS_REPORT__INIT;
  *message = init_value;
}
size_t sts__time_events_report__get_packed_size
                     (const Sts__TimeEventsReport *message)
{
  assert(message->base.descriptor == &sts__time_events_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sts__time_events_report__pack
                     (const Sts__TimeEventsReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sts__time_events_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sts__time_events_report__pack_to_buffer
                     (const Sts__TimeEventsReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sts__time_events_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sts__TimeEventsReport *
       sts__time_events_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sts__TimeEventsReport *)
     protobuf_c_message_unpack (&sts__time_events_report__descriptor,
                                allocator, len, data);
}
void   sts__time_events_report__free_unpacked
                     (Sts__TimeEventsReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sts__time_events_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sts__time_event__field_descriptors[6] =
{
  {
    "time",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Sts__TimeEvent, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cat",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Sts__TimeEvent, cat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Sts__TimeEvent, source),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subject",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Sts__TimeEvent, subject),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Sts__TimeEvent, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Sts__TimeEvent, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sts__time_event__field_indices_by_name[] = {
  1,   /* field[1] = cat */
  5,   /* field[5] = msg */
  4,   /* field[4] = seq */
  2,   /* field[2] = source */
  3,   /* field[3] = subject */
  0,   /* field[0] = time */
};
static const ProtobufCIntRange sts__time_event__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor sts__time_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sts.TimeEvent",
  "TimeEvent",
  "Sts__TimeEvent",
  "sts",
  sizeof(Sts__TimeEvent),
  6,
  sts__time_event__field_descriptors,
  sts__time_event__field_indices_by_name,
  2,  sts__time_event__number_ranges,
  (ProtobufCMessageInit) sts__time_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sts__device_id__field_descriptors[3] =
{
  {
    "node_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Sts__DeviceID, node_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firmware_version",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Sts__DeviceID, firmware_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Sts__DeviceID, location_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sts__device_id__field_indices_by_name[] = {
  1,   /* field[1] = firmware_version */
  2,   /* field[2] = location_id */
  0,   /* field[0] = node_id */
};
static const ProtobufCIntRange sts__device_id__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sts__device_id__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sts.DeviceID",
  "DeviceID",
  "Sts__DeviceID",
  "sts",
  sizeof(Sts__DeviceID),
  3,
  sts__device_id__field_descriptors,
  sts__device_id__field_indices_by_name,
  1,  sts__device_id__number_ranges,
  (ProtobufCMessageInit) sts__device_id__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sts__time_events_report__field_descriptors[5] =
{
  {
    "deviceID",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Sts__TimeEventsReport, deviceid),
    &sts__device_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seqNo",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Sts__TimeEventsReport, seqno),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "realTime",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Sts__TimeEventsReport, realtime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "monoTime",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Sts__TimeEventsReport, monotime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "events",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Sts__TimeEventsReport, n_events),
    offsetof(Sts__TimeEventsReport, events),
    &sts__time_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sts__time_events_report__field_indices_by_name[] = {
  0,   /* field[0] = deviceID */
  4,   /* field[4] = events */
  3,   /* field[3] = monoTime */
  2,   /* field[2] = realTime */
  1,   /* field[1] = seqNo */
};
static const ProtobufCIntRange sts__time_events_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sts__time_events_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sts.TimeEventsReport",
  "TimeEventsReport",
  "Sts__TimeEventsReport",
  "sts",
  sizeof(Sts__TimeEventsReport),
  5,
  sts__time_events_report__field_descriptors,
  sts__time_events_report__field_indices_by_name,
  1,  sts__time_events_report__number_ranges,
  (ProtobufCMessageInit) sts__time_events_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
