/*
Copyright (c) 2015, Plume Design Inc. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
   1. Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
   3. Neither the name of the Plume Design Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL Plume Design Inc. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: lte_info.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "lte_info.pb-c.h"
void   interfaces__lte_info__lte_info__init
                     (Interfaces__LteInfo__LteInfo         *message)
{
  static const Interfaces__LteInfo__LteInfo init_value = INTERFACES__LTE_INFO__LTE_INFO__INIT;
  *message = init_value;
}
size_t interfaces__lte_info__lte_info__get_packed_size
                     (const Interfaces__LteInfo__LteInfo *message)
{
  assert(message->base.descriptor == &interfaces__lte_info__lte_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t interfaces__lte_info__lte_info__pack
                     (const Interfaces__LteInfo__LteInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &interfaces__lte_info__lte_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t interfaces__lte_info__lte_info__pack_to_buffer
                     (const Interfaces__LteInfo__LteInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &interfaces__lte_info__lte_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Interfaces__LteInfo__LteInfo *
       interfaces__lte_info__lte_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Interfaces__LteInfo__LteInfo *)
     protobuf_c_message_unpack (&interfaces__lte_info__lte_info__descriptor,
                                allocator, len, data);
}
void   interfaces__lte_info__lte_info__free_unpacked
                     (Interfaces__LteInfo__LteInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &interfaces__lte_info__lte_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   interfaces__lte_info__lte_sig_qual__init
                     (Interfaces__LteInfo__LteSigQual         *message)
{
  static const Interfaces__LteInfo__LteSigQual init_value = INTERFACES__LTE_INFO__LTE_SIG_QUAL__INIT;
  *message = init_value;
}
size_t interfaces__lte_info__lte_sig_qual__get_packed_size
                     (const Interfaces__LteInfo__LteSigQual *message)
{
  assert(message->base.descriptor == &interfaces__lte_info__lte_sig_qual__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t interfaces__lte_info__lte_sig_qual__pack
                     (const Interfaces__LteInfo__LteSigQual *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &interfaces__lte_info__lte_sig_qual__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t interfaces__lte_info__lte_sig_qual__pack_to_buffer
                     (const Interfaces__LteInfo__LteSigQual *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &interfaces__lte_info__lte_sig_qual__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Interfaces__LteInfo__LteSigQual *
       interfaces__lte_info__lte_sig_qual__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Interfaces__LteInfo__LteSigQual *)
     protobuf_c_message_unpack (&interfaces__lte_info__lte_sig_qual__descriptor,
                                allocator, len, data);
}
void   interfaces__lte_info__lte_sig_qual__free_unpacked
                     (Interfaces__LteInfo__LteSigQual *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &interfaces__lte_info__lte_sig_qual__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   interfaces__lte_info__lte_net_serving_cell_info__init
                     (Interfaces__LteInfo__LteNetServingCellInfo         *message)
{
  static const Interfaces__LteInfo__LteNetServingCellInfo init_value = INTERFACES__LTE_INFO__LTE_NET_SERVING_CELL_INFO__INIT;
  *message = init_value;
}
size_t interfaces__lte_info__lte_net_serving_cell_info__get_packed_size
                     (const Interfaces__LteInfo__LteNetServingCellInfo *message)
{
  assert(message->base.descriptor == &interfaces__lte_info__lte_net_serving_cell_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t interfaces__lte_info__lte_net_serving_cell_info__pack
                     (const Interfaces__LteInfo__LteNetServingCellInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &interfaces__lte_info__lte_net_serving_cell_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t interfaces__lte_info__lte_net_serving_cell_info__pack_to_buffer
                     (const Interfaces__LteInfo__LteNetServingCellInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &interfaces__lte_info__lte_net_serving_cell_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Interfaces__LteInfo__LteNetServingCellInfo *
       interfaces__lte_info__lte_net_serving_cell_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Interfaces__LteInfo__LteNetServingCellInfo *)
     protobuf_c_message_unpack (&interfaces__lte_info__lte_net_serving_cell_info__descriptor,
                                allocator, len, data);
}
void   interfaces__lte_info__lte_net_serving_cell_info__free_unpacked
                     (Interfaces__LteInfo__LteNetServingCellInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &interfaces__lte_info__lte_net_serving_cell_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   interfaces__lte_info__lte_net_neighbor_cell_info__init
                     (Interfaces__LteInfo__LteNetNeighborCellInfo         *message)
{
  static const Interfaces__LteInfo__LteNetNeighborCellInfo init_value = INTERFACES__LTE_INFO__LTE_NET_NEIGHBOR_CELL_INFO__INIT;
  *message = init_value;
}
size_t interfaces__lte_info__lte_net_neighbor_cell_info__get_packed_size
                     (const Interfaces__LteInfo__LteNetNeighborCellInfo *message)
{
  assert(message->base.descriptor == &interfaces__lte_info__lte_net_neighbor_cell_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t interfaces__lte_info__lte_net_neighbor_cell_info__pack
                     (const Interfaces__LteInfo__LteNetNeighborCellInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &interfaces__lte_info__lte_net_neighbor_cell_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t interfaces__lte_info__lte_net_neighbor_cell_info__pack_to_buffer
                     (const Interfaces__LteInfo__LteNetNeighborCellInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &interfaces__lte_info__lte_net_neighbor_cell_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Interfaces__LteInfo__LteNetNeighborCellInfo *
       interfaces__lte_info__lte_net_neighbor_cell_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Interfaces__LteInfo__LteNetNeighborCellInfo *)
     protobuf_c_message_unpack (&interfaces__lte_info__lte_net_neighbor_cell_info__descriptor,
                                allocator, len, data);
}
void   interfaces__lte_info__lte_net_neighbor_cell_info__free_unpacked
                     (Interfaces__LteInfo__LteNetNeighborCellInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &interfaces__lte_info__lte_net_neighbor_cell_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   interfaces__lte_info__lte_info_report__init
                     (Interfaces__LteInfo__LteInfoReport         *message)
{
  static const Interfaces__LteInfo__LteInfoReport init_value = INTERFACES__LTE_INFO__LTE_INFO_REPORT__INIT;
  *message = init_value;
}
size_t interfaces__lte_info__lte_info_report__get_packed_size
                     (const Interfaces__LteInfo__LteInfoReport *message)
{
  assert(message->base.descriptor == &interfaces__lte_info__lte_info_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t interfaces__lte_info__lte_info_report__pack
                     (const Interfaces__LteInfo__LteInfoReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &interfaces__lte_info__lte_info_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t interfaces__lte_info__lte_info_report__pack_to_buffer
                     (const Interfaces__LteInfo__LteInfoReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &interfaces__lte_info__lte_info_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Interfaces__LteInfo__LteInfoReport *
       interfaces__lte_info__lte_info_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Interfaces__LteInfo__LteInfoReport *)
     protobuf_c_message_unpack (&interfaces__lte_info__lte_info_report__descriptor,
                                allocator, len, data);
}
void   interfaces__lte_info__lte_info_report__free_unpacked
                     (Interfaces__LteInfo__LteInfoReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &interfaces__lte_info__lte_info_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor interfaces__lte_info__lte_info__field_descriptors[9] =
{
  {
    "prod_id_info",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteInfo, prod_id_info),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chip_serial",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteInfo, chip_serial),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imei",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteInfo, imei),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imsi",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteInfo, imsi),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iccid",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteInfo, iccid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sim_status",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteInfo, sim_status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "net_reg_status",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteInfo, net_reg_status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "service_provider_name",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteInfo, service_provider_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sim_slot",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteInfo, sim_slot),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned interfaces__lte_info__lte_info__field_indices_by_name[] = {
  1,   /* field[1] = chip_serial */
  4,   /* field[4] = iccid */
  2,   /* field[2] = imei */
  3,   /* field[3] = imsi */
  6,   /* field[6] = net_reg_status */
  0,   /* field[0] = prod_id_info */
  7,   /* field[7] = service_provider_name */
  8,   /* field[8] = sim_slot */
  5,   /* field[5] = sim_status */
};
static const ProtobufCIntRange interfaces__lte_info__lte_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor interfaces__lte_info__lte_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "interfaces.lte_info.LteInfo",
  "LteInfo",
  "Interfaces__LteInfo__LteInfo",
  "interfaces.lte_info",
  sizeof(Interfaces__LteInfo__LteInfo),
  9,
  interfaces__lte_info__lte_info__field_descriptors,
  interfaces__lte_info__lte_info__field_indices_by_name,
  1,  interfaces__lte_info__lte_info__number_ranges,
  (ProtobufCMessageInit) interfaces__lte_info__lte_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor interfaces__lte_info__lte_sig_qual__field_descriptors[2] =
{
  {
    "rssi",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteSigQual, rssi),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ber",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteSigQual, ber),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned interfaces__lte_info__lte_sig_qual__field_indices_by_name[] = {
  1,   /* field[1] = ber */
  0,   /* field[0] = rssi */
};
static const ProtobufCIntRange interfaces__lte_info__lte_sig_qual__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor interfaces__lte_info__lte_sig_qual__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "interfaces.lte_info.LteSigQual",
  "LteSigQual",
  "Interfaces__LteInfo__LteSigQual",
  "interfaces.lte_info",
  sizeof(Interfaces__LteInfo__LteSigQual),
  2,
  interfaces__lte_info__lte_sig_qual__field_descriptors,
  interfaces__lte_info__lte_sig_qual__field_indices_by_name,
  1,  interfaces__lte_info__lte_sig_qual__number_ranges,
  (ProtobufCMessageInit) interfaces__lte_info__lte_sig_qual__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor interfaces__lte_info__lte_net_serving_cell_info__field_descriptors[18] =
{
  {
    "cell_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, cell_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, state),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_tdd",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, is_tdd),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mcc",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, mcc),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mnc",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, mnc),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cellid",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, cellid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pcid",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, pcid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uarfcn",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, uarfcn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "earfcn",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, earfcn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freq_band",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, freq_band),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ul_bandwidth",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, ul_bandwidth),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dl_bandwidth",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, dl_bandwidth),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tac",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, tac),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rsrp",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, rsrp),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rsrq",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, rsrq),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, rssi),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sinr",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, sinr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "srxlev",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetServingCellInfo, srxlev),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned interfaces__lte_info__lte_net_serving_cell_info__field_indices_by_name[] = {
  0,   /* field[0] = cell_type */
  5,   /* field[5] = cellid */
  11,   /* field[11] = dl_bandwidth */
  8,   /* field[8] = earfcn */
  9,   /* field[9] = freq_band */
  2,   /* field[2] = is_tdd */
  3,   /* field[3] = mcc */
  4,   /* field[4] = mnc */
  6,   /* field[6] = pcid */
  13,   /* field[13] = rsrp */
  14,   /* field[14] = rsrq */
  15,   /* field[15] = rssi */
  16,   /* field[16] = sinr */
  17,   /* field[17] = srxlev */
  1,   /* field[1] = state */
  12,   /* field[12] = tac */
  7,   /* field[7] = uarfcn */
  10,   /* field[10] = ul_bandwidth */
};
static const ProtobufCIntRange interfaces__lte_info__lte_net_serving_cell_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 18 }
};
const ProtobufCMessageDescriptor interfaces__lte_info__lte_net_serving_cell_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "interfaces.lte_info.LteNetServingCellInfo",
  "LteNetServingCellInfo",
  "Interfaces__LteInfo__LteNetServingCellInfo",
  "interfaces.lte_info",
  sizeof(Interfaces__LteInfo__LteNetServingCellInfo),
  18,
  interfaces__lte_info__lte_net_serving_cell_info__field_descriptors,
  interfaces__lte_info__lte_net_serving_cell_info__field_indices_by_name,
  1,  interfaces__lte_info__lte_net_serving_cell_info__number_ranges,
  (ProtobufCMessageInit) interfaces__lte_info__lte_net_serving_cell_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor interfaces__lte_info__lte_net_neighbor_cell_info__field_descriptors[23] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, mode),
    &interfaces__lte_info__lte_neighbor_cell_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freq_mode",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, freq_mode),
    &interfaces__lte_info__lte_neighbor_freq_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "earfcn",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, earfcn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uarfcn",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, uarfcn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pcid",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, pcid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rsrq",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, rsrq),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rsrp",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, rsrp),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, rssi),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sinr",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, sinr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "srxlev_base_station",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, srxlev_base_station),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cell_resel_priority",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, cell_resel_priority),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_non_intra_search",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, s_non_intra_search),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thresh_serving_low",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, thresh_serving_low),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_intra_search",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, s_intra_search),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thresh_x_low",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, thresh_x_low),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thresh_x_high",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, thresh_x_high),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "psc",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, psc),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rscp",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, rscp),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ecno",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, ecno),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, set),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rank",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, rank),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cellid",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, cellid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "srxlev_inter_freq",
    23,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteNetNeighborCellInfo, srxlev_inter_freq),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned interfaces__lte_info__lte_net_neighbor_cell_info__field_indices_by_name[] = {
  10,   /* field[10] = cell_resel_priority */
  21,   /* field[21] = cellid */
  2,   /* field[2] = earfcn */
  18,   /* field[18] = ecno */
  1,   /* field[1] = freq_mode */
  0,   /* field[0] = mode */
  4,   /* field[4] = pcid */
  16,   /* field[16] = psc */
  20,   /* field[20] = rank */
  17,   /* field[17] = rscp */
  6,   /* field[6] = rsrp */
  5,   /* field[5] = rsrq */
  7,   /* field[7] = rssi */
  13,   /* field[13] = s_intra_search */
  11,   /* field[11] = s_non_intra_search */
  19,   /* field[19] = set */
  8,   /* field[8] = sinr */
  9,   /* field[9] = srxlev_base_station */
  22,   /* field[22] = srxlev_inter_freq */
  12,   /* field[12] = thresh_serving_low */
  15,   /* field[15] = thresh_x_high */
  14,   /* field[14] = thresh_x_low */
  3,   /* field[3] = uarfcn */
};
static const ProtobufCIntRange interfaces__lte_info__lte_net_neighbor_cell_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 23 }
};
const ProtobufCMessageDescriptor interfaces__lte_info__lte_net_neighbor_cell_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "interfaces.lte_info.LteNetNeighborCellInfo",
  "LteNetNeighborCellInfo",
  "Interfaces__LteInfo__LteNetNeighborCellInfo",
  "interfaces.lte_info",
  sizeof(Interfaces__LteInfo__LteNetNeighborCellInfo),
  23,
  interfaces__lte_info__lte_net_neighbor_cell_info__field_descriptors,
  interfaces__lte_info__lte_net_neighbor_cell_info__field_indices_by_name,
  1,  interfaces__lte_info__lte_net_neighbor_cell_info__number_ranges,
  (ProtobufCMessageInit) interfaces__lte_info__lte_net_neighbor_cell_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor interfaces__lte_info__lte_info_report__field_descriptors[5] =
{
  {
    "if_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteInfoReport, if_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lte_info",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteInfoReport, lte_info),
    &interfaces__lte_info__lte_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lte_sig_qual",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteInfoReport, lte_sig_qual),
    &interfaces__lte_info__lte_sig_qual__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lte_srv_cell",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Interfaces__LteInfo__LteInfoReport, lte_srv_cell),
    &interfaces__lte_info__lte_net_serving_cell_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lte_neigh_cell_info",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Interfaces__LteInfo__LteInfoReport, n_lte_neigh_cell_info),
    offsetof(Interfaces__LteInfo__LteInfoReport, lte_neigh_cell_info),
    &interfaces__lte_info__lte_net_neighbor_cell_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned interfaces__lte_info__lte_info_report__field_indices_by_name[] = {
  0,   /* field[0] = if_name */
  1,   /* field[1] = lte_info */
  4,   /* field[4] = lte_neigh_cell_info */
  2,   /* field[2] = lte_sig_qual */
  3,   /* field[3] = lte_srv_cell */
};
static const ProtobufCIntRange interfaces__lte_info__lte_info_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor interfaces__lte_info__lte_info_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "interfaces.lte_info.LteInfoReport",
  "LteInfoReport",
  "Interfaces__LteInfo__LteInfoReport",
  "interfaces.lte_info",
  sizeof(Interfaces__LteInfo__LteInfoReport),
  5,
  interfaces__lte_info__lte_info_report__field_descriptors,
  interfaces__lte_info__lte_info_report__field_indices_by_name,
  1,  interfaces__lte_info__lte_info_report__number_ranges,
  (ProtobufCMessageInit) interfaces__lte_info__lte_info_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue interfaces__lte_info__lte_neighbor_cell_mode__enum_values_by_number[3] =
{
  { "LTE_CELL_MODE_UNSPECIFIED", "INTERFACES__LTE_INFO__LTE_NEIGHBOR_CELL_MODE__LTE_CELL_MODE_UNSPECIFIED", 0 },
  { "LTE_CELL_MODE_LTE", "INTERFACES__LTE_INFO__LTE_NEIGHBOR_CELL_MODE__LTE_CELL_MODE_LTE", 1 },
  { "LTE_CELL_MODE_WCDMA", "INTERFACES__LTE_INFO__LTE_NEIGHBOR_CELL_MODE__LTE_CELL_MODE_WCDMA", 2 },
};
static const ProtobufCIntRange interfaces__lte_info__lte_neighbor_cell_mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex interfaces__lte_info__lte_neighbor_cell_mode__enum_values_by_name[3] =
{
  { "LTE_CELL_MODE_LTE", 1 },
  { "LTE_CELL_MODE_UNSPECIFIED", 0 },
  { "LTE_CELL_MODE_WCDMA", 2 },
};
const ProtobufCEnumDescriptor interfaces__lte_info__lte_neighbor_cell_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "interfaces.lte_info.LteNeighborCellMode",
  "LteNeighborCellMode",
  "Interfaces__LteInfo__LteNeighborCellMode",
  "interfaces.lte_info",
  3,
  interfaces__lte_info__lte_neighbor_cell_mode__enum_values_by_number,
  3,
  interfaces__lte_info__lte_neighbor_cell_mode__enum_values_by_name,
  1,
  interfaces__lte_info__lte_neighbor_cell_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue interfaces__lte_info__lte_neighbor_freq_mode__enum_values_by_number[5] =
{
  { "LTE_FREQ_MODE_UNSPECIFIED", "INTERFACES__LTE_INFO__LTE_NEIGHBOR_FREQ_MODE__LTE_FREQ_MODE_UNSPECIFIED", 0 },
  { "LTE_FREQ_MODE_INTRA", "INTERFACES__LTE_INFO__LTE_NEIGHBOR_FREQ_MODE__LTE_FREQ_MODE_INTRA", 1 },
  { "LTE_FREQ_MODE_INTER", "INTERFACES__LTE_INFO__LTE_NEIGHBOR_FREQ_MODE__LTE_FREQ_MODE_INTER", 2 },
  { "LTE_FREQ_MODE_WCDMA", "INTERFACES__LTE_INFO__LTE_NEIGHBOR_FREQ_MODE__LTE_FREQ_MODE_WCDMA", 3 },
  { "LTE_FREQ_MODE_WCDMA_LTE", "INTERFACES__LTE_INFO__LTE_NEIGHBOR_FREQ_MODE__LTE_FREQ_MODE_WCDMA_LTE", 4 },
};
static const ProtobufCIntRange interfaces__lte_info__lte_neighbor_freq_mode__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex interfaces__lte_info__lte_neighbor_freq_mode__enum_values_by_name[5] =
{
  { "LTE_FREQ_MODE_INTER", 2 },
  { "LTE_FREQ_MODE_INTRA", 1 },
  { "LTE_FREQ_MODE_UNSPECIFIED", 0 },
  { "LTE_FREQ_MODE_WCDMA", 3 },
  { "LTE_FREQ_MODE_WCDMA_LTE", 4 },
};
const ProtobufCEnumDescriptor interfaces__lte_info__lte_neighbor_freq_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "interfaces.lte_info.LteNeighborFreqMode",
  "LteNeighborFreqMode",
  "Interfaces__LteInfo__LteNeighborFreqMode",
  "interfaces.lte_info",
  5,
  interfaces__lte_info__lte_neighbor_freq_mode__enum_values_by_number,
  5,
  interfaces__lte_info__lte_neighbor_freq_mode__enum_values_by_name,
  1,
  interfaces__lte_info__lte_neighbor_freq_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
