/*
Copyright (c) 2015, Plume Design Inc. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
   1. Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
   3. Neither the name of the Plume Design Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL Plume Design Inc. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dpi_stats.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "dpi_stats.pb-c.h"
void   interfaces__dpi_stats__dpi_stats_observation_point__init
                     (Interfaces__DpiStats__DpiStatsObservationPoint         *message)
{
  static const Interfaces__DpiStats__DpiStatsObservationPoint init_value = INTERFACES__DPI_STATS__DPI_STATS_OBSERVATION_POINT__INIT;
  *message = init_value;
}
size_t interfaces__dpi_stats__dpi_stats_observation_point__get_packed_size
                     (const Interfaces__DpiStats__DpiStatsObservationPoint *message)
{
  assert(message->base.descriptor == &interfaces__dpi_stats__dpi_stats_observation_point__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t interfaces__dpi_stats__dpi_stats_observation_point__pack
                     (const Interfaces__DpiStats__DpiStatsObservationPoint *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &interfaces__dpi_stats__dpi_stats_observation_point__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t interfaces__dpi_stats__dpi_stats_observation_point__pack_to_buffer
                     (const Interfaces__DpiStats__DpiStatsObservationPoint *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &interfaces__dpi_stats__dpi_stats_observation_point__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Interfaces__DpiStats__DpiStatsObservationPoint *
       interfaces__dpi_stats__dpi_stats_observation_point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Interfaces__DpiStats__DpiStatsObservationPoint *)
     protobuf_c_message_unpack (&interfaces__dpi_stats__dpi_stats_observation_point__descriptor,
                                allocator, len, data);
}
void   interfaces__dpi_stats__dpi_stats_observation_point__free_unpacked
                     (Interfaces__DpiStats__DpiStatsObservationPoint *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &interfaces__dpi_stats__dpi_stats_observation_point__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   interfaces__dpi_stats__dpi_stats_counters__init
                     (Interfaces__DpiStats__DpiStatsCounters         *message)
{
  static const Interfaces__DpiStats__DpiStatsCounters init_value = INTERFACES__DPI_STATS__DPI_STATS_COUNTERS__INIT;
  *message = init_value;
}
size_t interfaces__dpi_stats__dpi_stats_counters__get_packed_size
                     (const Interfaces__DpiStats__DpiStatsCounters *message)
{
  assert(message->base.descriptor == &interfaces__dpi_stats__dpi_stats_counters__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t interfaces__dpi_stats__dpi_stats_counters__pack
                     (const Interfaces__DpiStats__DpiStatsCounters *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &interfaces__dpi_stats__dpi_stats_counters__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t interfaces__dpi_stats__dpi_stats_counters__pack_to_buffer
                     (const Interfaces__DpiStats__DpiStatsCounters *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &interfaces__dpi_stats__dpi_stats_counters__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Interfaces__DpiStats__DpiStatsCounters *
       interfaces__dpi_stats__dpi_stats_counters__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Interfaces__DpiStats__DpiStatsCounters *)
     protobuf_c_message_unpack (&interfaces__dpi_stats__dpi_stats_counters__descriptor,
                                allocator, len, data);
}
void   interfaces__dpi_stats__dpi_stats_counters__free_unpacked
                     (Interfaces__DpiStats__DpiStatsCounters *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &interfaces__dpi_stats__dpi_stats_counters__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   interfaces__dpi_stats__dpi_stats_report__init
                     (Interfaces__DpiStats__DpiStatsReport         *message)
{
  static const Interfaces__DpiStats__DpiStatsReport init_value = INTERFACES__DPI_STATS__DPI_STATS_REPORT__INIT;
  *message = init_value;
}
size_t interfaces__dpi_stats__dpi_stats_report__get_packed_size
                     (const Interfaces__DpiStats__DpiStatsReport *message)
{
  assert(message->base.descriptor == &interfaces__dpi_stats__dpi_stats_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t interfaces__dpi_stats__dpi_stats_report__pack
                     (const Interfaces__DpiStats__DpiStatsReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &interfaces__dpi_stats__dpi_stats_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t interfaces__dpi_stats__dpi_stats_report__pack_to_buffer
                     (const Interfaces__DpiStats__DpiStatsReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &interfaces__dpi_stats__dpi_stats_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Interfaces__DpiStats__DpiStatsReport *
       interfaces__dpi_stats__dpi_stats_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Interfaces__DpiStats__DpiStatsReport *)
     protobuf_c_message_unpack (&interfaces__dpi_stats__dpi_stats_report__descriptor,
                                allocator, len, data);
}
void   interfaces__dpi_stats__dpi_stats_report__free_unpacked
                     (Interfaces__DpiStats__DpiStatsReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &interfaces__dpi_stats__dpi_stats_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor interfaces__dpi_stats__dpi_stats_observation_point__field_descriptors[2] =
{
  {
    "node_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsObservationPoint, node_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsObservationPoint, location_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned interfaces__dpi_stats__dpi_stats_observation_point__field_indices_by_name[] = {
  1,   /* field[1] = location_id */
  0,   /* field[0] = node_id */
};
static const ProtobufCIntRange interfaces__dpi_stats__dpi_stats_observation_point__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor interfaces__dpi_stats__dpi_stats_observation_point__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "interfaces.dpi_stats.DpiStatsObservationPoint",
  "DpiStatsObservationPoint",
  "Interfaces__DpiStats__DpiStatsObservationPoint",
  "interfaces.dpi_stats",
  sizeof(Interfaces__DpiStats__DpiStatsObservationPoint),
  2,
  interfaces__dpi_stats__dpi_stats_observation_point__field_descriptors,
  interfaces__dpi_stats__dpi_stats_observation_point__field_indices_by_name,
  1,  interfaces__dpi_stats__dpi_stats_observation_point__number_ranges,
  (ProtobufCMessageInit) interfaces__dpi_stats__dpi_stats_observation_point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor interfaces__dpi_stats__dpi_stats_counters__field_descriptors[13] =
{
  {
    "curr_alloc",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsCounters, curr_alloc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peak_alloc",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsCounters, peak_alloc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fail_alloc",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsCounters, fail_alloc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mpmc_events",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsCounters, mpmc_events),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scan_started",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsCounters, scan_started),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scan_stopped",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsCounters, scan_stopped),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scan_bytes",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsCounters, scan_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "err_incomplete",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsCounters, err_incomplete),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "err_length",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsCounters, err_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "err_create",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsCounters, err_create),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "err_scan",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsCounters, err_scan),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connections",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsCounters, connections),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "streams",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsCounters, streams),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned interfaces__dpi_stats__dpi_stats_counters__field_indices_by_name[] = {
  11,   /* field[11] = connections */
  0,   /* field[0] = curr_alloc */
  9,   /* field[9] = err_create */
  7,   /* field[7] = err_incomplete */
  8,   /* field[8] = err_length */
  10,   /* field[10] = err_scan */
  2,   /* field[2] = fail_alloc */
  3,   /* field[3] = mpmc_events */
  1,   /* field[1] = peak_alloc */
  6,   /* field[6] = scan_bytes */
  4,   /* field[4] = scan_started */
  5,   /* field[5] = scan_stopped */
  12,   /* field[12] = streams */
};
static const ProtobufCIntRange interfaces__dpi_stats__dpi_stats_counters__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor interfaces__dpi_stats__dpi_stats_counters__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "interfaces.dpi_stats.DpiStatsCounters",
  "DpiStatsCounters",
  "Interfaces__DpiStats__DpiStatsCounters",
  "interfaces.dpi_stats",
  sizeof(Interfaces__DpiStats__DpiStatsCounters),
  13,
  interfaces__dpi_stats__dpi_stats_counters__field_descriptors,
  interfaces__dpi_stats__dpi_stats_counters__field_indices_by_name,
  1,  interfaces__dpi_stats__dpi_stats_counters__number_ranges,
  (ProtobufCMessageInit) interfaces__dpi_stats__dpi_stats_counters__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor interfaces__dpi_stats__dpi_stats_report__field_descriptors[3] =
{
  {
    "observation_point",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsReport, observation_point),
    &interfaces__dpi_stats__dpi_stats_observation_point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "plugin",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsReport, plugin),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "counters",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Interfaces__DpiStats__DpiStatsReport, counters),
    &interfaces__dpi_stats__dpi_stats_counters__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned interfaces__dpi_stats__dpi_stats_report__field_indices_by_name[] = {
  2,   /* field[2] = counters */
  0,   /* field[0] = observation_point */
  1,   /* field[1] = plugin */
};
static const ProtobufCIntRange interfaces__dpi_stats__dpi_stats_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor interfaces__dpi_stats__dpi_stats_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "interfaces.dpi_stats.DpiStatsReport",
  "DpiStatsReport",
  "Interfaces__DpiStats__DpiStatsReport",
  "interfaces.dpi_stats",
  sizeof(Interfaces__DpiStats__DpiStatsReport),
  3,
  interfaces__dpi_stats__dpi_stats_report__field_descriptors,
  interfaces__dpi_stats__dpi_stats_report__field_indices_by_name,
  1,  interfaces__dpi_stats__dpi_stats_report__number_ranges,
  (ProtobufCMessageInit) interfaces__dpi_stats__dpi_stats_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
