/*
Copyright (c) 2015, Plume Design Inc. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
   1. Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
   3. Neither the name of the Plume Design Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL Plume Design Inc. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/*
 * schema_consts.h
 */
#ifndef SCHEMA_CONSTS_H_INCLUDED
#define SCHEMA_CONSTS_H_INCLUDED

/* interfaces/opensync.ovsschema constants not generated by schema ... */

#define SCHEMA_CONSTS_RADIO_TYPE_STR_2G     "2.4G"
#define SCHEMA_CONSTS_RADIO_TYPE_STR_5G     "5G"
#define SCHEMA_CONSTS_RADIO_TYPE_STR_5GL    "5GL"
#define SCHEMA_CONSTS_RADIO_TYPE_STR_5GU    "5GU"
#define SCHEMA_CONSTS_RADIO_TYPE_STR_6G     "6G"

#define SCHEMA_CONSTS_SCAN_TYPE_ON_CHAN "on-chan"
#define SCHEMA_CONSTS_SCAN_TYPE_OFF_CHAN "off-chan"
#define SCHEMA_CONSTS_SCAN_TYPE_FULL "full"

#define SCHEMA_CONSTS_REPORT_TYPE_NEIGHBOR "neighbor"
#define SCHEMA_CONSTS_REPORT_TYPE_CLIENT "client"
#define SCHEMA_CONSTS_REPORT_TYPE_SURVEY "survey"

/* Interface types */
#define SCHEMA_CONSTS_IF_TYPE_ETH           "eth"
#define SCHEMA_CONSTS_IF_TYPE_LTE           "lte"
#define SCHEMA_CONSTS_IF_TYPE_PPPOE         "pppoe"
#define SCHEMA_CONSTS_IF_TYPE_VLAN          "vlan"
#define SCHEMA_CONSTS_IF_TYPE_GRE           "gre"
#define SCHEMA_CONSTS_IF_TYPE_GRE6          "gre6"
#define SCHEMA_CONSTS_IF_TYPE_VIF           "vif"

/* Cloud Radio ifname's */
#define SCHEMA_CONSTS_RADIO_PHY_NAME_2G     "wifi0"
#define SCHEMA_CONSTS_RADIO_PHY_NAME_5G     "wifi1"
#define SCHEMA_CONSTS_RADIO_PHY_NAME_5GL    "wifi1"
#define SCHEMA_CONSTS_RADIO_PHY_NAME_5GU    "wifi2"
#define SCHEMA_CONSTS_RADIO_PHY_NAME_6G     "wifi2"

#define SCHEMA_CONSTS_IF_NAME_PREFIX_HOME   "home"
#define SCHEMA_CONSTS_IF_NAME_PREFIX_BHAUL  "bhaul"
#define SCHEMA_CONSTS_IF_NAME_PREFIX_GUEST  "guest"

/* Cloud VIF type */
typedef enum {
    SCHEMA_CONSTS_VIF_TYPE_NONE = 0,
    SCHEMA_CONSTS_VIF_TYPE_BHAUL,
    SCHEMA_CONSTS_VIF_TYPE_HOME,
    SCHEMA_CONSTS_VIF_TYPE_GUEST
} schema_consts_vif_type_t;

/* Cloud bridge ifname's */
#define SCHEMA_CONSTS_BR_NAME_WAN            "br-wan"
#define SCHEMA_CONSTS_BR_NAME_HOME           "br-home"
#define SCHEMA_CONSTS_BR_NAME_GUEST          "br-guest"

/* Channel selection mode */
#define SCHEMA_CONSTS_CH_MODE_CLOUD          "cloud"
#define SCHEMA_CONSTS_CH_MODE_AUTO           "auto"
#define SCHEMA_CONSTS_CH_MODE_MANUAL         "manual"

#define SCHEMA_CONSTS_DEVICE_MODE_CLOUD      "cloud"
#define SCHEMA_CONSTS_DEVICE_MODE_MONITOR    "monitor"
#define SCHEMA_CONSTS_DEVICE_MODE_BATTERY    "battery"
#define SCHEMA_CONSTS_DEVICE_MODE_CUSTOM     "custom"

#define SCHEMA_CONSTS_SSID_BROAD_ENABLED     "enabled"
#define SCHEMA_CONSTS_SSID_BROAD_DISABLED    "disabled"

#define SCHEMA_CONSTS_VIF_MODE_AP            "ap"
#define SCHEMA_CONSTS_VIF_MODE_STA           "sta"

#define SCHEMA_CONSTS_MAC_TYPE_NONE          "none"
#define SCHEMA_CONSTS_MAC_TYPE_BLACKLIST     "blacklist"
#define SCHEMA_CONSTS_MAC_TYPE_WHITELIST     "whitelist"

#define SCHEMA_CONSTS_DM_CMD_REBOOT          "reboot"
#define SCHEMA_CONSTS_DM_CMD_RESTART         "restart"
#define SCHEMA_CONSTS_DM_CMD_EXECUTE         "execute"

/* VIF security */
#define SCHEMA_CONSTS_SECURITY_KEY              "key"
#define SCHEMA_CONSTS_SECURITY_MODE             "mode"
#define SCHEMA_CONSTS_SECURITY_RADIUS_IP        "radius_server_ip"
#define SCHEMA_CONSTS_SECURITY_RADIUS_PORT      "radius_server_port"
#define SCHEMA_CONSTS_SECURITY_RADIUS_SECRET    "radius_server_secret"

#define SCHEMA_CONSTS_SECURITY_ENCRYPT          "encryption"
#define SCHEMA_CONSTS_SECURITY_ENCRYPT_OPEN     "OPEN"

#define SCHEMA_CONSTS_SECURITY_ENCRYPT_WEP      "WEP"
#define SCHEMA_CONSTS_SECURITY_ENCRYPT_WEP_64   "64"
#define SCHEMA_CONSTS_SECURITY_ENCRYPT_WEP_128  "128"

#define SCHEMA_CONSTS_SECURITY_ENCRYPT_WPA      "WPA-PSK"
#define SCHEMA_CONSTS_SECURITY_ENCRYPT_WPA_EAP  "WPA-EAP"
#define SCHEMA_CONSTS_SECURITY_ENCRYPT_WPA_1    "1"
#define SCHEMA_CONSTS_SECURITY_ENCRYPT_WPA_2    "2"
#define SCHEMA_CONSTS_SECURITY_ENCRYPT_WPA_MIX  "mixed"

#define SCHEMA_CONSTS_SECURITY_PMF_DISABLED     "disabled"
#define SCHEMA_CONSTS_SECURITY_PMF_OPTIONAL     "optional"
#define SCHEMA_CONSTS_SECURITY_PMF_REQUIRED     "required"

#define SCHEMA_CONSTS_INET_ENABLED          "enabled"
#define SCHEMA_CONSTS_INET_DNS              "dns"
#define SCHEMA_CONSTS_INET_DNS_PRIMARY      "primary"
#define SCHEMA_CONSTS_INET_DNS_SECONDARY    "secondary"

#define SCHEMA_CONSTS_INET_IP_SCHEME_DHCP   "dhcp"
#define SCHEMA_CONSTS_INET_IP_SCHEME_STATIC "static"

#define SCHEMA_CONSTS_INET_DHCPD            "dhcpd"

#define SCHEMA_CONSTS_INET_DHCP_OPTION      "dhcp_option"
#define SCHEMA_CONSTS_INET_DHCP_IP_START    "start"
#define SCHEMA_CONSTS_INET_DHCP_IP_STOP     "stop"
#define SCHEMA_CONSTS_INET_DHCP_LEASE_TIME  "lease_time"
#define SCHEMA_CONSTS_INET_DHCP_FORCE       "force"

#define SCHEMA_CONSTS_KEY_WPA_PSK           "wpa-psk"
#define SCHEMA_CONSTS_KEY_WPA_PSK_SHA256    "wpa-psk-sha256"
#define SCHEMA_CONSTS_KEY_WPA_EAP           "wpa-eap"
#define SCHEMA_CONSTS_KEY_WPA_EAP_SHA256    "wpa-eap-sha256"
#define SCHEMA_CONSTS_KEY_WPA_EAP_B_192     "wpa-eap-suite-b-192"
#define SCHEMA_CONSTS_KEY_FT_SAE            "ft-sae"
#define SCHEMA_CONSTS_KEY_FT_PSK            "ft-psk"
#define SCHEMA_CONSTS_KEY_FT_EAP            "ft-eap"
#define SCHEMA_CONSTS_KEY_FT_EAP_SHA384     "ft-eap-sha384"
#define SCHEMA_CONSTS_KEY_DPP               "dpp"
#define SCHEMA_CONSTS_KEY_SAE               "sae"
#define SCHEMA_CONSTS_KEY_OWE               "owe"
/* legacy and deprecated */
#define SCHEMA_CONSTS_KEY_WPA2_PSK          "wpa2-psk"
#define SCHEMA_CONSTS_KEY_WPA2_EAP          "wpa2-eap"
#define SCHEMA_CONSTS_KEY_FT_WPA2_PSK       "ft-wpa2-psk"

#define SCHEMA_CONSTS_CIPHER_RSN_NONE     "rsn-none"
#define SCHEMA_CONSTS_CIPHER_RSN_WEP      "wep"
#define SCHEMA_CONSTS_CIPHER_RSN_TKIP     "rsn-tkip"
#define SCHEMA_CONSTS_CIPHER_RSN_CCMP     "rsn-ccmp"
#define SCHEMA_CONSTS_CIPHER_RSN_BIP_CMAC "bip-cmac"
#define SCHEMA_CONSTS_CIPHER_WPA_NONE     "wpa-none"
#define SCHEMA_CONSTS_CIPHER_WPA_TKIP     "wpa-tkip"
#define SCHEMA_CONSTS_CIPHER_WPA_CCMP     "wpa-ccmp"

#define SCHEMA_CONSTS_DPP_INIT_ON_ANNOUNCE "initiate_on_announce"
#define SCHEMA_CONSTS_DPP_INIT_NOW         "initiate_now"
#define SCHEMA_CONSTS_DPP_RESPOND_ONLY     "respond_only"
#define SCHEMA_CONSTS_DPP_CHIRP            "chirp_and_respond"

#define SCHEMA_CONSTS_DPP_AKM_UNKNOWN     "unknown"
#define SCHEMA_CONSTS_DPP_AKM_PSK         "psk"
#define SCHEMA_CONSTS_DPP_AKM_SAE         "sae"
#define SCHEMA_CONSTS_DPP_AKM_PSK_SAE     "psk-sae"
#define SCHEMA_CONSTS_DPP_AKM_DPP         "dpp"
#define SCHEMA_CONSTS_DPP_AKM_DPP_SAE     "dpp-sae"
#define SCHEMA_CONSTS_DPP_AKM_DPP_PSK_SAE "dpp-psk-sae"

#define SCHEMA_CONSTS_DPP_REQUESTED   "requested"
#define SCHEMA_CONSTS_DPP_IN_PROGRESS "in_progress"
#define SCHEMA_CONSTS_DPP_TIMED_OUT   "timed_out"
#define SCHEMA_CONSTS_DPP_FAILED      "failed"
#define SCHEMA_CONSTS_DPP_SUCCEEDED   "succeeded"

#define SCHEMA_CONSTS_DPP_PRIME256V1      "prime256v1"
#define SCHEMA_CONSTS_DPP_SECP384R1       "secp384r1"
#define SCHEMA_CONSTS_DPP_SECP521R1       "secp521r1"
#define SCHEMA_CONSTS_DPP_BRAINPOOLP256R1 "brainpoolP256r1"
#define SCHEMA_CONSTS_DPP_BRAINPOOLP384R1 "brainpoolP384r1"
#define SCHEMA_CONSTS_DPP_BRAINPOOLP512R1 "brainpoolP512r1"

#define SCHEMA_CONSTS_DPP_STA_DPP "sta-dpp"
#define SCHEMA_CONSTS_DPP_STA_PSK "sta-psk"
#define SCHEMA_CONSTS_DPP_AP_DPP  "ap-dpp"
#define SCHEMA_CONSTS_DPP_AP_PSK  "ap-psk"

#endif /* SCHEMA_CONSTS_H_INCLUDED */
