/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: stats_pub.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "stats_pub.pb-c.h"
void   sts_pub__survey__init
                     (StsPub__Survey         *message)
{
  static StsPub__Survey init_value = STS_PUB__SURVEY__INIT;
  *message = init_value;
}
size_t sts_pub__survey__get_packed_size
                     (const StsPub__Survey *message)
{
  assert(message->base.descriptor == &sts_pub__survey__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sts_pub__survey__pack
                     (const StsPub__Survey *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sts_pub__survey__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sts_pub__survey__pack_to_buffer
                     (const StsPub__Survey *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sts_pub__survey__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StsPub__Survey *
       sts_pub__survey__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StsPub__Survey *)
     protobuf_c_message_unpack (&sts_pub__survey__descriptor,
                                allocator, len, data);
}
void   sts_pub__survey__free_unpacked
                     (StsPub__Survey *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sts_pub__survey__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sts_pub__device__init
                     (StsPub__Device         *message)
{
  static StsPub__Device init_value = STS_PUB__DEVICE__INIT;
  *message = init_value;
}
size_t sts_pub__device__get_packed_size
                     (const StsPub__Device *message)
{
  assert(message->base.descriptor == &sts_pub__device__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sts_pub__device__pack
                     (const StsPub__Device *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sts_pub__device__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sts_pub__device__pack_to_buffer
                     (const StsPub__Device *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sts_pub__device__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StsPub__Device *
       sts_pub__device__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StsPub__Device *)
     protobuf_c_message_unpack (&sts_pub__device__descriptor,
                                allocator, len, data);
}
void   sts_pub__device__free_unpacked
                     (StsPub__Device *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sts_pub__device__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sts_pub__client__init
                     (StsPub__Client         *message)
{
  static StsPub__Client init_value = STS_PUB__CLIENT__INIT;
  *message = init_value;
}
size_t sts_pub__client__get_packed_size
                     (const StsPub__Client *message)
{
  assert(message->base.descriptor == &sts_pub__client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sts_pub__client__pack
                     (const StsPub__Client *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sts_pub__client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sts_pub__client__pack_to_buffer
                     (const StsPub__Client *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sts_pub__client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StsPub__Client *
       sts_pub__client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StsPub__Client *)
     protobuf_c_message_unpack (&sts_pub__client__descriptor,
                                allocator, len, data);
}
void   sts_pub__client__free_unpacked
                     (StsPub__Client *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sts_pub__client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sts_pub__survey__field_descriptors[7] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StsPub__Survey, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "busy",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StsPub__Survey, busy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "busy_tx",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StsPub__Survey, busy_tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "busy_rx",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StsPub__Survey, busy_rx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "busy_self",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StsPub__Survey, busy_self),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "busy_ext",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StsPub__Survey, busy_ext),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "noise_floor",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(StsPub__Survey, noise_floor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sts_pub__survey__field_indices_by_name[] = {
  1,   /* field[1] = busy */
  5,   /* field[5] = busy_ext */
  3,   /* field[3] = busy_rx */
  4,   /* field[4] = busy_self */
  2,   /* field[2] = busy_tx */
  6,   /* field[6] = noise_floor */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange sts_pub__survey__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor sts_pub__survey__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sts_pub.Survey",
  "Survey",
  "StsPub__Survey",
  "sts_pub",
  sizeof(StsPub__Survey),
  7,
  sts_pub__survey__field_descriptors,
  sts_pub__survey__field_indices_by_name,
  1,  sts_pub__survey__number_ranges,
  (ProtobufCMessageInit) sts_pub__survey__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sts_pub__device__field_descriptors[7] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StsPub__Device, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_total",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StsPub__Device, mem_total),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_used",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StsPub__Device, mem_used),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu_util",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StsPub__Device, cpu_util),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu_util_1m",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(StsPub__Device, cpu_util_1m),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu_util_5m",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(StsPub__Device, cpu_util_5m),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu_util_15m",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(StsPub__Device, cpu_util_15m),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sts_pub__device__field_indices_by_name[] = {
  3,   /* field[3] = cpu_util */
  6,   /* field[6] = cpu_util_15m */
  4,   /* field[4] = cpu_util_1m */
  5,   /* field[5] = cpu_util_5m */
  1,   /* field[1] = mem_total */
  2,   /* field[2] = mem_used */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange sts_pub__device__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor sts_pub__device__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sts_pub.Device",
  "Device",
  "StsPub__Device",
  "sts_pub",
  sizeof(StsPub__Device),
  7,
  sts_pub__device__field_descriptors,
  sts_pub__device__field_indices_by_name,
  1,  sts_pub__device__number_ranges,
  (ProtobufCMessageInit) sts_pub__device__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sts_pub__client__field_descriptors[12] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StsPub__Client, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes_tx",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StsPub__Client, bytes_tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes_rx",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StsPub__Client, bytes_rx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frames_tx",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StsPub__Client, frames_tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frames_rx",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StsPub__Client, frames_rx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "retries_rx",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StsPub__Client, retries_rx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "retries_tx",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StsPub__Client, retries_tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errors_rx",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StsPub__Client, errors_rx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errors_tx",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StsPub__Client, errors_tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rate_rx",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(StsPub__Client, rate_rx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rate_tx",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(StsPub__Client, rate_tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(StsPub__Client, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sts_pub__client__field_indices_by_name[] = {
  2,   /* field[2] = bytes_rx */
  1,   /* field[1] = bytes_tx */
  7,   /* field[7] = errors_rx */
  8,   /* field[8] = errors_tx */
  4,   /* field[4] = frames_rx */
  3,   /* field[3] = frames_tx */
  9,   /* field[9] = rate_rx */
  10,   /* field[10] = rate_tx */
  5,   /* field[5] = retries_rx */
  6,   /* field[6] = retries_tx */
  11,   /* field[11] = rssi */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange sts_pub__client__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor sts_pub__client__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sts_pub.Client",
  "Client",
  "StsPub__Client",
  "sts_pub",
  sizeof(StsPub__Client),
  12,
  sts_pub__client__field_descriptors,
  sts_pub__client__field_indices_by_name,
  2,  sts_pub__client__number_ranges,
  (ProtobufCMessageInit) sts_pub__client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
