/*
Copyright (c) 2015, Plume Design Inc. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
   1. Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
   3. Neither the name of the Plume Design Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL Plume Design Inc. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef CONST_IEEE80211_H_INCLUDED
#define CONST_IEEE80211_H_INCLUDED

#include <const.h>

#define C_IEEE80211_FC_VERSION 0x0003
#define C_IEEE80211_FC_TYPE    0x000c
#define C_IEEE80211_FC_SUBTYPE 0x00f0
#define C_IEEE80211_FC_TODS    0x0100
#define C_IEEE80211_FC_FROMDS  0x0200

#define C_IEEE80211_FC_TYPE_MGMT 0
#define C_IEEE80211_FC_TYPE_CTRL 1
#define C_IEEE80211_FC_TYPE_DATA 2
#define C_IEEE80211_FC_TYPE_EXT  3

#define C_IEEE80211_FC_MGMT_SUBTYPE_ASSOC_REQ     0
#define C_IEEE80211_FC_MGMT_SUBTYPE_ASSOC_RESP    1
#define C_IEEE80211_FC_MGMT_SUBTYPE_REASSOC_REQ   2
#define C_IEEE80211_FC_MGMT_SUBTYPE_REASSOC_RESP  3
#define C_IEEE80211_FC_MGMT_SUBTYPE_PROBE_REQ     4
#define C_IEEE80211_FC_MGMT_SUBTYPE_PROBE_RESP    5
#define C_IEEE80211_FC_MGMT_SUBTYPE_TIMING_ADV    6
#define C_IEEE80211_FC_MGMT_SUBTYPE_RESERVED0     7
#define C_IEEE80211_FC_MGMT_SUBTYPE_BEACON        8
#define C_IEEE80211_FC_MGMT_SUBTYPE_ATIM          9
#define C_IEEE80211_FC_MGMT_SUBTYPE_DISASSOC      10
#define C_IEEE80211_FC_MGMT_SUBTYPE_AUTH          11
#define C_IEEE80211_FC_MGMT_SUBTYPE_DEAUTH        12
#define C_IEEE80211_FC_MGMT_SUBTYPE_ACTION        13
#define C_IEEE80211_FC_MGMT_SUBTYPE_ACTION_NO_ACK 14
#define C_IEEE80211_FC_MGMT_SUBTYPE_RESERVED1     15

#define C_IEEE80211_EID_NEIGH_REPORT 52  /* 0x34 */
#define C_IEEE80211_EID_VENDOR       221 /* 0xdd */

#define C_IEEE80211_NR_EID_BSS_TRANS_CAND_PREF 3

#define C_IEEE80211_ACTION_CAT_WNM 10

#define C_IEEE80211_WNM_BTM_QUERY 6
#define C_IEEE80211_WNM_BTM_REQ   7
#define C_IEEE80211_WNM_BTM_RESP  8

#define C_IEEE80211_BTM_REQ_PREF_CAND             C_BIT(0)
#define C_IEEE80211_BTM_REQ_ABRIDGED              C_BIT(1)
#define C_IEEE80211_BTM_REQ_DISASSOC_IMMINENT     C_BIT(2)
#define C_IEEE80211_BTM_REQ_BSS_TERM              C_BIT(3)
#define C_IEEE80211_BTM_REQ_ESS_DISASSOC_IMMINENT C_BIT(4)

#define C_IEEE80211_BTM_RESP_STATUS_ACCEPT                         0
#define C_IEEE80211_BTM_RESP_STATUS_REJECT_UNSPECIFIED             1
#define C_IEEE80211_BTM_RESP_STATUS_REJECT_INSUFFICIENT_BSS_DATA   2
#define C_IEEE80211_BTM_RESP_STATUS_REJECT_INSUFFICIENT_CAPACITY   3
#define C_IEEE80211_BTM_RESP_STATUS_REJECT_BSS_TERM_UNDESIRED      4
#define C_IEEE80211_BTM_RESP_STATUS_REJECT_BSS_TERM_DELAY_REQUEST  5
#define C_IEEE80211_BTM_RESP_STATUS_REJECT_CANDIDATE_LIST_PROVIDED 6
#define C_IEEE80211_BTM_RESP_STATUS_REJECT_NO_SUITABLE_BSS         7
#define C_IEEE80211_BTM_RESP_STATUS_REJECT_LEAVING_ESS             8

#define C_IEEE80211_WFA_OUI_BYTE0 0x50
#define C_IEEE80211_WFA_OUI_BYTE1 0x6f
#define C_IEEE80211_WFA_OUI_BYTE2 0x9a

#define C_IEEE80211_MBO_OUI_TYPE        0x16
#define C_IEEE80211_MBO_ATTR_CELL_PREF  5
#define C_IEEE80211_MBO_ATTR_BTM_REASON 6

#define C_IEEE80211_MBO_CELL_PREF_EXCLUDE        0
#define C_IEEE80211_MBO_CELL_PREF_SHOULD_NOT_USE 1
#define C_IEEE80211_MBO_CELL_PREF_SHOULD_USE     255

#define C_IEEE80211_MBO_BTM_REASON_UNSPECIFIED 0
#define C_IEEE80211_MBO_BTM_REASON_LOW_RSSI    5

#endif /* CONST_IEEE80211_H_INCLUDED */
