#!/bin/sh
ref_client_update_wlan0=$(cat <<-.
	CLIENT_UPDATE
	mac=20:00:00:00:00:00
	if_name=wlan0
	blacklist=false
	rssi_probe_hwm=1
	rssi_probe_lwm=20
	rssi_auth_hwm=1
	rssi_auth_lwm=0
	rssi_inact_xing=0
	rssi_high_xing=35
	rssi_low_xing=20
	auth_reject_reason=0
.
)
ref_client_update_wlan1=$(cat <<-.
	CLIENT_UPDATE
	mac=20:00:00:00:00:00
	if_name=wlan1
	blacklist=false
	rssi_probe_hwm=0
	rssi_probe_lwm=0
	rssi_auth_hwm=0
	rssi_auth_lwm=0
	rssi_inact_xing=0
	rssi_high_xing=0
	rssi_low_xing=20
	auth_reject_reason=0
.
)
ref_client_update_wlan2=$(cat <<-.
	CLIENT_UPDATE
	mac=20:00:00:00:00:00
	if_name=wlan2
	blacklist=false
	rssi_probe_hwm=0
	rssi_probe_lwm=0
	rssi_auth_hwm=0
	rssi_auth_lwm=0
	rssi_inact_xing=0
	rssi_high_xing=0
	rssi_low_xing=0
	auth_reject_reason=0
.
)
ref_remove_neighbor_wlan0_ext_1100=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan0
	bssid=AA:AA:AA:AA:11:00
.
)
ref_remove_neighbor_wlan1_ext_1100=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan1
	bssid=AA:AA:AA:AA:11:00
.
)
ref_remove_neighbor_wlan2_ext_1100=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan2
	bssid=AA:AA:AA:AA:11:00
.
)
ref_remove_neighbor_wlan0_ext_1101=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan0
	bssid=AA:AA:AA:AA:11:01
.
)
ref_remove_neighbor_wlan1_ext_1101=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan1
	bssid=AA:AA:AA:AA:11:01
.
)
ref_remove_neighbor_wlan2_ext_1101=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan2
	bssid=AA:AA:AA:AA:11:01
.
)
ref_remove_neighbor_wlan0_ext_1102=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan0
	bssid=AA:AA:AA:AA:11:02
.
)
ref_remove_neighbor_wlan1_ext_1102=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan1
	bssid=AA:AA:AA:AA:11:02
.
)
ref_remove_neighbor_wlan2_ext_1102=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan2
	bssid=AA:AA:AA:AA:11:02
.
)
ref_remove_neighbor_wlan0_ext_1103=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan0
	bssid=AA:AA:AA:AA:11:03
.
)
ref_remove_neighbor_wlan1_ext_1103=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan1
	bssid=AA:AA:AA:AA:11:03
.
)
ref_remove_neighbor_wlan2_ext_1103=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan2
	bssid=AA:AA:AA:AA:11:03
.
)
ref_remove_neighbor_wlan0_self_00=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan0
	bssid=10:00:00:00:00:00
.
)
ref_remove_neighbor_wlan0_self_01=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan0
	bssid=10:00:00:00:00:01
.
)
ref_remove_neighbor_wlan0_self_02=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan0
	bssid=10:00:00:00:00:02
.
)
ref_remove_neighbor_wlan1_self_00=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan1
	bssid=10:00:00:00:00:00
.
)
ref_remove_neighbor_wlan1_self_01=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan1
	bssid=10:00:00:00:00:01
.
)
ref_remove_neighbor_wlan1_self_02=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan1
	bssid=10:00:00:00:00:02
.
)
ref_remove_neighbor_wlan2_self_00=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan2
	bssid=10:00:00:00:00:00
.
)
ref_remove_neighbor_wlan2_self_01=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan2
	bssid=10:00:00:00:00:01
.
)
ref_remove_neighbor_wlan2_self_02=$(cat <<-.
	REMOVE_NEIGHBOR
	if_name=wlan2
	bssid=10:00:00:00:00:02
.
)
ref_set_neighbor_wlan0_ext_1100=$(cat <<-.
	SET_NEIGHBOR
	if_name=wlan0
	bssid=AA:AA:AA:AA:11:00
	bssid_info=143
	op_class=118
	channel=52
	phy_type=9
	opt_subelems=
	opt_subelems_len=0
.
)
ref_set_neighbor_wlan1_ext_1100=$(cat <<-.
	SET_NEIGHBOR
	if_name=wlan1
	bssid=AA:AA:AA:AA:11:00
	bssid_info=143
	op_class=118
	channel=52
	phy_type=9
	opt_subelems=
	opt_subelems_len=0
.
)
ref_set_neighbor_wlan2_ext_1100=$(cat <<-.
	SET_NEIGHBOR
	if_name=wlan2
	bssid=AA:AA:AA:AA:11:00
	bssid_info=143
	op_class=118
	channel=52
	phy_type=9
	opt_subelems=
	opt_subelems_len=0
.
)
ref_set_neighbor_wlan0_ext_1101=$(cat <<-.
	SET_NEIGHBOR
	if_name=wlan0
	bssid=AA:AA:AA:AA:11:01
	bssid_info=143
	op_class=118
	channel=60
	phy_type=9
	opt_subelems=
	opt_subelems_len=0
.
)
ref_set_neighbor_wlan1_ext_1101=$(cat <<-.
	SET_NEIGHBOR
	if_name=wlan1
	bssid=AA:AA:AA:AA:11:01
	bssid_info=143
	op_class=118
	channel=60
	phy_type=9
	opt_subelems=
	opt_subelems_len=0
.
)
ref_set_neighbor_wlan2_ext_1101=$(cat <<-.
	SET_NEIGHBOR
	if_name=wlan2
	bssid=AA:AA:AA:AA:11:01
	bssid_info=143
	op_class=118
	channel=60
	phy_type=9
	opt_subelems=
	opt_subelems_len=0
.
)
ref_set_neighbor_wlan0_ext_1102=$(cat <<-.
	SET_NEIGHBOR
	if_name=wlan0
	bssid=AA:AA:AA:AA:11:02
	bssid_info=143
	op_class=121
	channel=100
	phy_type=9
	opt_subelems=
	opt_subelems_len=0
.
)
ref_set_neighbor_wlan1_ext_1102=$(cat <<-.
	SET_NEIGHBOR
	if_name=wlan1
	bssid=AA:AA:AA:AA:11:02
	bssid_info=143
	op_class=121
	channel=100
	phy_type=9
	opt_subelems=
	opt_subelems_len=0
.
)
ref_set_neighbor_wlan2_ext_1102=$(cat <<-.
	SET_NEIGHBOR
	if_name=wlan2
	bssid=AA:AA:AA:AA:11:02
	bssid_info=143
	op_class=121
	channel=100
	phy_type=9
	opt_subelems=
	opt_subelems_len=0
.
)
ref_set_neighbor_wlan0_ext_1103=$(cat <<-.
	SET_NEIGHBOR
	if_name=wlan0
	bssid=AA:AA:AA:AA:11:03
	bssid_info=143
	op_class=121
	channel=108
	phy_type=9
	opt_subelems=
	opt_subelems_len=0
.
)
ref_set_neighbor_wlan1_ext_1103=$(cat <<-.
	SET_NEIGHBOR
	if_name=wlan1
	bssid=AA:AA:AA:AA:11:03
	bssid_info=143
	op_class=121
	channel=108
	phy_type=9
	opt_subelems=
	opt_subelems_len=0
.
)
ref_set_neighbor_wlan2_ext_1103=$(cat <<-.
	SET_NEIGHBOR
	if_name=wlan2
	bssid=AA:AA:AA:AA:11:03
	bssid_info=143
	op_class=121
	channel=108
	phy_type=9
	opt_subelems=
	opt_subelems_len=0
.
)
ref_first_btm_req=$(cat <<-.
	BTM_REQUEST
	mac=20:00:00:00:00:00
	ifname=wlan1
	neighs=
	    bssid=AA:AA:AA:AA:11:00
	    bssid_info=143
	    op_class=118
	    phy_type=9
	    opt_subelems=
	    opt_subelems_len=0

	    bssid=AA:AA:AA:AA:11:03
	    bssid_info=143
	    op_class=121
	    phy_type=9
	    opt_subelems=
	    opt_subelems_len=0

	    bssid=10:00:00:00:00:01
	    bssid_info=143
	    op_class=115
	    phy_type=9
	    opt_subelems=
	    opt_subelems_len=0

	num_neigh=3
	valid_int=255
	abridged=1
	pref=1
	disassoc_imminent=0
	bss_term=0
	tries=0
	max_tries=1
	retry_interval=1
	inc_neigh=true
	inc_self=true
.
)
ref_first_btm_req_retry=$(cat <<-.
	BTM_REQUEST
	mac=20:00:00:00:00:00
	ifname=wlan1
	neighs=
	    bssid=AA:AA:AA:AA:11:00
	    bssid_info=143
	    op_class=118
	    phy_type=9
	    opt_subelems=
	    opt_subelems_len=0

	    bssid=AA:AA:AA:AA:11:03
	    bssid_info=143
	    op_class=121
	    phy_type=9
	    opt_subelems=
	    opt_subelems_len=0

	    bssid=10:00:00:00:00:01
	    bssid_info=143
	    op_class=115
	    phy_type=9
	    opt_subelems=
	    opt_subelems_len=0

	num_neigh=3
	valid_int=255
	abridged=1
	pref=1
	disassoc_imminent=0
	bss_term=0
	tries=2
	max_tries=1
	retry_interval=1
	inc_neigh=true
	inc_self=true
.
)
ref_second_btm_req=$(cat <<-.
	BTM_REQUEST
	mac=20:00:00:00:00:00
	ifname=wlan1
	neighs=
	    bssid=AA:AA:AA:AA:11:03
	    bssid_info=143
	    op_class=121
	    phy_type=9
	    opt_subelems=
	    opt_subelems_len=0

	    bssid=AA:AA:AA:AA:11:02
	    bssid_info=143
	    op_class=121
	    phy_type=9
	    opt_subelems=
	    opt_subelems_len=0

	    bssid=10:00:00:00:00:01
	    bssid_info=143
	    op_class=115
	    phy_type=9
	    opt_subelems=
	    opt_subelems_len=0

	num_neigh=3
	valid_int=255
	abridged=1
	pref=1
	disassoc_imminent=0
	bss_term=0
	tries=0
	max_tries=1
	retry_interval=1
	inc_neigh=true
	inc_self=true
.
)
