#!/bin/sh -axe

update_sta() {
	. ./case-pre-assoc-2_4-5ghz-timer_common_vars || return 1

	eval dut=\$$1

	$dut <<. || return $?
		ovsh u Band_Steering_Clients \
			-w mac==20:00:00:00:00:00  \
			max_rejects:=0 \
			rejects_tmout_secs:=0 \
			pref_5g_pre_assoc_block_timeout_msecs:=90000
.

	diff_vars "$ref_update_sta_24" "$(timeout 1 bsal_sim read /${1}_bsal_out)" || return 1
	diff_vars "$ref_update_sta_5" "$(timeout 1 bsal_sim read /${1}_bsal_out)" || return 1
	diff_vars "$ref_update_sta_6" "$(timeout 1 bsal_sim read /${1}_bsal_out)" || return 1
}
