#!/bin/sh -axe

# This test verifies whether BM can correctly enter STEERING, then BACKOFF and
# finally clean up configuration after BACKOFF expires.

. ./common || return 1
. ./case-pre-assoc-2_4-5ghz-timer_common || return 1
. ./case-pre-assoc-2_4-5ghz-timer-backoff-expire_vars || return 1

prepare_dut dut_ap_a || return 1
add_sta dut_ap_a || return 1
update_sta dut_ap_a || return 1

# Send few 5 GHz probes
bsal_sim write /dut_ap_a_bsal_in "PROBE mac=20:00:00:00:00:00 if_name=wlan1 snr=50 ssid=true blocked=false" || return 1
sleep 1
bsal_sim write /dut_ap_a_bsal_in "PROBE mac=20:00:00:00:00:00 if_name=wlan1 snr=50 ssid=true blocked=false" || return 1
sleep 1

# Send 2.4 GHz probes
bsal_sim write /dut_ap_a_bsal_in "PROBE mac=20:00:00:00:00:00 if_name=wlan0 snr=50 ssid=true blocked=true" || return 1
sleep 1
bsal_sim write /dut_ap_a_bsal_in "PROBE mac=20:00:00:00:00:00 if_name=wlan0 snr=50 ssid=true blocked=true" || return 1
sleep 1
bsal_sim write /dut_ap_a_bsal_in "PROBE mac=20:00:00:00:00:00 if_name=wlan0 snr=50 ssid=true blocked=true" || return 1
sleep 1
bsal_sim write /dut_ap_a_bsal_in "PROBE mac=20:00:00:00:00:00 if_name=wlan0 snr=50 ssid=true blocked=true" || return 1
sleep 1
bsal_sim write /dut_ap_a_bsal_in "PROBE mac=20:00:00:00:00:00 if_name=wlan0 snr=50 ssid=true blocked=true" || return 1
sleep 1
bsal_sim write /dut_ap_a_bsal_in "PROBE mac=20:00:00:00:00:00 if_name=wlan0 snr=50 ssid=true blocked=true" || return 1
sleep 1
bsal_sim write /dut_ap_a_bsal_in "PROBE mac=20:00:00:00:00:00 if_name=wlan0 snr=50 ssid=true blocked=true" || return 1
sleep 1
bsal_sim write /dut_ap_a_bsal_in "PROBE mac=20:00:00:00:00:00 if_name=wlan0 snr=50 ssid=true blocked=true" || return 1
sleep 1
bsal_sim write /dut_ap_a_bsal_in "PROBE mac=20:00:00:00:00:00 if_name=wlan0 snr=50 ssid=true blocked=true" || return 1
sleep 1
bsal_sim write /dut_ap_a_bsal_in "PROBE mac=20:00:00:00:00:00 if_name=wlan0 snr=50 ssid=true blocked=true" || return 1

sleep 100

diff_vars "$ref_dpp_client_during_backoff" "$(timeout 1 bsal_sim read /dut_ap_a_dpp_out)" || return 1
diff_vars "$ref_update_sta_24_during_backoff" "$(timeout 1 bsal_sim read /dut_ap_a_bsal_out)" || return 1
diff_vars "$ref_update_sta_5_during_backoff" "$(timeout 1 bsal_sim read /dut_ap_a_bsal_out)" || return 1

sleep 120
diff_vars "$ref_dpp_client_after_backoff_expire" "$(timeout 1 bsal_sim read /dut_ap_a_dpp_out)" || return 1
diff_vars "$ref_update_sta_24_after_backoff_expire" "$(timeout 1 bsal_sim read /dut_ap_a_bsal_out)" || return 1
diff_vars "$ref_update_sta_5_after_backoff_expire" "$(timeout 1 bsal_sim read /dut_ap_a_bsal_out)" || return 1
