#!/bin/sh
set -axe

wd=$(readlink -f "$(dirname "$0")")
test_cases=$(find $wd -maxdepth 1 -name 'case-*' ! -name '*_vars' ! -name '*_common' -exec basename {} \;)

$wd/run-uml.prepare
parallel -j $(nproc) --tag --lb --halt now,fail=1 "$wd/run-uml {1} </dev/null" ::: ${test_cases}

set +x

printf "================================================================================\n"
printf "    SUMMARY\n"
printf "================================================================================\n"

passed=0
total=0

for test_case in $test_cases
do
    if test "$(cat $wd/logs/$test_case/result)" = "SUCCESS"
    then
        echo "SUCCESS   $test_case"
        passed=$(($passed + 1))
    else
        echo "FAIL      $test_case"
    fi
    total=$(($total + 1))
done

printf "\n%d of %d tests passed\n" $passed $total
