#!/bin/sh -axe
db=$(readlink -f core/work/native-*/rootfs/usr/opensync/etc/conf.db.bck)
wm=$(readlink -f core/work/native-*/bin/wm)
ovsh=$(readlink -f core/work/native-*/bin/ovsh)
self=$(readlink -f "$0")
dir=$(dirname "$self")
conf=$dir/conf.db
sock=$dir/db.sock

cd "$dir"
cp -v "$db" "$conf"

DUMMY_WM_CMD=./$1
WM2_DPP_RECALC_SECONDS=0
PLUME_OVSDB_SOCK_PATH=$sock

exec ovsdb-server \
	--remote=punix:$sock \
	--run "$wm" \
	"$conf"
