/*
Copyright (c) 2015, Plume Design Inc. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
   1. Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
   3. Neither the name of the Plume Design Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL Plume Design Inc. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gatekeeper_hero_stats.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gatekeeper_hero_stats.pb-c.h"
void   gatekeeper__hero_stats__hero_observation_point__init
                     (Gatekeeper__HeroStats__HeroObservationPoint         *message)
{
  static const Gatekeeper__HeroStats__HeroObservationPoint init_value = GATEKEEPER__HERO_STATS__HERO_OBSERVATION_POINT__INIT;
  *message = init_value;
}
size_t gatekeeper__hero_stats__hero_observation_point__get_packed_size
                     (const Gatekeeper__HeroStats__HeroObservationPoint *message)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_observation_point__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gatekeeper__hero_stats__hero_observation_point__pack
                     (const Gatekeeper__HeroStats__HeroObservationPoint *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_observation_point__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gatekeeper__hero_stats__hero_observation_point__pack_to_buffer
                     (const Gatekeeper__HeroStats__HeroObservationPoint *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_observation_point__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gatekeeper__HeroStats__HeroObservationPoint *
       gatekeeper__hero_stats__hero_observation_point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gatekeeper__HeroStats__HeroObservationPoint *)
     protobuf_c_message_unpack (&gatekeeper__hero_stats__hero_observation_point__descriptor,
                                allocator, len, data);
}
void   gatekeeper__hero_stats__hero_observation_point__free_unpacked
                     (Gatekeeper__HeroStats__HeroObservationPoint *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_observation_point__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gatekeeper__hero_stats__hero_hostname__init
                     (Gatekeeper__HeroStats__HeroHostname         *message)
{
  static const Gatekeeper__HeroStats__HeroHostname init_value = GATEKEEPER__HERO_STATS__HERO_HOSTNAME__INIT;
  *message = init_value;
}
size_t gatekeeper__hero_stats__hero_hostname__get_packed_size
                     (const Gatekeeper__HeroStats__HeroHostname *message)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_hostname__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gatekeeper__hero_stats__hero_hostname__pack
                     (const Gatekeeper__HeroStats__HeroHostname *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_hostname__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gatekeeper__hero_stats__hero_hostname__pack_to_buffer
                     (const Gatekeeper__HeroStats__HeroHostname *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_hostname__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gatekeeper__HeroStats__HeroHostname *
       gatekeeper__hero_stats__hero_hostname__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gatekeeper__HeroStats__HeroHostname *)
     protobuf_c_message_unpack (&gatekeeper__hero_stats__hero_hostname__descriptor,
                                allocator, len, data);
}
void   gatekeeper__hero_stats__hero_hostname__free_unpacked
                     (Gatekeeper__HeroStats__HeroHostname *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_hostname__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gatekeeper__hero_stats__hero_url__init
                     (Gatekeeper__HeroStats__HeroUrl         *message)
{
  static const Gatekeeper__HeroStats__HeroUrl init_value = GATEKEEPER__HERO_STATS__HERO_URL__INIT;
  *message = init_value;
}
size_t gatekeeper__hero_stats__hero_url__get_packed_size
                     (const Gatekeeper__HeroStats__HeroUrl *message)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_url__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gatekeeper__hero_stats__hero_url__pack
                     (const Gatekeeper__HeroStats__HeroUrl *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_url__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gatekeeper__hero_stats__hero_url__pack_to_buffer
                     (const Gatekeeper__HeroStats__HeroUrl *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_url__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gatekeeper__HeroStats__HeroUrl *
       gatekeeper__hero_stats__hero_url__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gatekeeper__HeroStats__HeroUrl *)
     protobuf_c_message_unpack (&gatekeeper__hero_stats__hero_url__descriptor,
                                allocator, len, data);
}
void   gatekeeper__hero_stats__hero_url__free_unpacked
                     (Gatekeeper__HeroStats__HeroUrl *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_url__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gatekeeper__hero_stats__hero_ipv4__init
                     (Gatekeeper__HeroStats__HeroIpv4         *message)
{
  static const Gatekeeper__HeroStats__HeroIpv4 init_value = GATEKEEPER__HERO_STATS__HERO_IPV4__INIT;
  *message = init_value;
}
size_t gatekeeper__hero_stats__hero_ipv4__get_packed_size
                     (const Gatekeeper__HeroStats__HeroIpv4 *message)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_ipv4__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gatekeeper__hero_stats__hero_ipv4__pack
                     (const Gatekeeper__HeroStats__HeroIpv4 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_ipv4__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gatekeeper__hero_stats__hero_ipv4__pack_to_buffer
                     (const Gatekeeper__HeroStats__HeroIpv4 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_ipv4__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gatekeeper__HeroStats__HeroIpv4 *
       gatekeeper__hero_stats__hero_ipv4__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gatekeeper__HeroStats__HeroIpv4 *)
     protobuf_c_message_unpack (&gatekeeper__hero_stats__hero_ipv4__descriptor,
                                allocator, len, data);
}
void   gatekeeper__hero_stats__hero_ipv4__free_unpacked
                     (Gatekeeper__HeroStats__HeroIpv4 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_ipv4__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gatekeeper__hero_stats__hero_ipv6__init
                     (Gatekeeper__HeroStats__HeroIpv6         *message)
{
  static const Gatekeeper__HeroStats__HeroIpv6 init_value = GATEKEEPER__HERO_STATS__HERO_IPV6__INIT;
  *message = init_value;
}
size_t gatekeeper__hero_stats__hero_ipv6__get_packed_size
                     (const Gatekeeper__HeroStats__HeroIpv6 *message)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_ipv6__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gatekeeper__hero_stats__hero_ipv6__pack
                     (const Gatekeeper__HeroStats__HeroIpv6 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_ipv6__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gatekeeper__hero_stats__hero_ipv6__pack_to_buffer
                     (const Gatekeeper__HeroStats__HeroIpv6 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_ipv6__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gatekeeper__HeroStats__HeroIpv6 *
       gatekeeper__hero_stats__hero_ipv6__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gatekeeper__HeroStats__HeroIpv6 *)
     protobuf_c_message_unpack (&gatekeeper__hero_stats__hero_ipv6__descriptor,
                                allocator, len, data);
}
void   gatekeeper__hero_stats__hero_ipv6__free_unpacked
                     (Gatekeeper__HeroStats__HeroIpv6 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_ipv6__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gatekeeper__hero_stats__hero_app__init
                     (Gatekeeper__HeroStats__HeroApp         *message)
{
  static const Gatekeeper__HeroStats__HeroApp init_value = GATEKEEPER__HERO_STATS__HERO_APP__INIT;
  *message = init_value;
}
size_t gatekeeper__hero_stats__hero_app__get_packed_size
                     (const Gatekeeper__HeroStats__HeroApp *message)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_app__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gatekeeper__hero_stats__hero_app__pack
                     (const Gatekeeper__HeroStats__HeroApp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_app__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gatekeeper__hero_stats__hero_app__pack_to_buffer
                     (const Gatekeeper__HeroStats__HeroApp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_app__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gatekeeper__HeroStats__HeroApp *
       gatekeeper__hero_stats__hero_app__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gatekeeper__HeroStats__HeroApp *)
     protobuf_c_message_unpack (&gatekeeper__hero_stats__hero_app__descriptor,
                                allocator, len, data);
}
void   gatekeeper__hero_stats__hero_app__free_unpacked
                     (Gatekeeper__HeroStats__HeroApp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_app__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gatekeeper__hero_stats__hero_ipv4_flow_tuple__init
                     (Gatekeeper__HeroStats__HeroIpv4FlowTuple         *message)
{
  static const Gatekeeper__HeroStats__HeroIpv4FlowTuple init_value = GATEKEEPER__HERO_STATS__HERO_IPV4_FLOW_TUPLE__INIT;
  *message = init_value;
}
size_t gatekeeper__hero_stats__hero_ipv4_flow_tuple__get_packed_size
                     (const Gatekeeper__HeroStats__HeroIpv4FlowTuple *message)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_ipv4_flow_tuple__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gatekeeper__hero_stats__hero_ipv4_flow_tuple__pack
                     (const Gatekeeper__HeroStats__HeroIpv4FlowTuple *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_ipv4_flow_tuple__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gatekeeper__hero_stats__hero_ipv4_flow_tuple__pack_to_buffer
                     (const Gatekeeper__HeroStats__HeroIpv4FlowTuple *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_ipv4_flow_tuple__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gatekeeper__HeroStats__HeroIpv4FlowTuple *
       gatekeeper__hero_stats__hero_ipv4_flow_tuple__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gatekeeper__HeroStats__HeroIpv4FlowTuple *)
     protobuf_c_message_unpack (&gatekeeper__hero_stats__hero_ipv4_flow_tuple__descriptor,
                                allocator, len, data);
}
void   gatekeeper__hero_stats__hero_ipv4_flow_tuple__free_unpacked
                     (Gatekeeper__HeroStats__HeroIpv4FlowTuple *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_ipv4_flow_tuple__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gatekeeper__hero_stats__hero_ipv6_flow_tuple__init
                     (Gatekeeper__HeroStats__HeroIpv6FlowTuple         *message)
{
  static const Gatekeeper__HeroStats__HeroIpv6FlowTuple init_value = GATEKEEPER__HERO_STATS__HERO_IPV6_FLOW_TUPLE__INIT;
  *message = init_value;
}
size_t gatekeeper__hero_stats__hero_ipv6_flow_tuple__get_packed_size
                     (const Gatekeeper__HeroStats__HeroIpv6FlowTuple *message)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_ipv6_flow_tuple__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gatekeeper__hero_stats__hero_ipv6_flow_tuple__pack
                     (const Gatekeeper__HeroStats__HeroIpv6FlowTuple *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_ipv6_flow_tuple__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gatekeeper__hero_stats__hero_ipv6_flow_tuple__pack_to_buffer
                     (const Gatekeeper__HeroStats__HeroIpv6FlowTuple *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_ipv6_flow_tuple__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gatekeeper__HeroStats__HeroIpv6FlowTuple *
       gatekeeper__hero_stats__hero_ipv6_flow_tuple__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gatekeeper__HeroStats__HeroIpv6FlowTuple *)
     protobuf_c_message_unpack (&gatekeeper__hero_stats__hero_ipv6_flow_tuple__descriptor,
                                allocator, len, data);
}
void   gatekeeper__hero_stats__hero_ipv6_flow_tuple__free_unpacked
                     (Gatekeeper__HeroStats__HeroIpv6FlowTuple *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_ipv6_flow_tuple__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gatekeeper__hero_stats__hero_stats__init
                     (Gatekeeper__HeroStats__HeroStats         *message)
{
  static const Gatekeeper__HeroStats__HeroStats init_value = GATEKEEPER__HERO_STATS__HERO_STATS__INIT;
  *message = init_value;
}
size_t gatekeeper__hero_stats__hero_stats__get_packed_size
                     (const Gatekeeper__HeroStats__HeroStats *message)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gatekeeper__hero_stats__hero_stats__pack
                     (const Gatekeeper__HeroStats__HeroStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gatekeeper__hero_stats__hero_stats__pack_to_buffer
                     (const Gatekeeper__HeroStats__HeroStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gatekeeper__HeroStats__HeroStats *
       gatekeeper__hero_stats__hero_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gatekeeper__HeroStats__HeroStats *)
     protobuf_c_message_unpack (&gatekeeper__hero_stats__hero_stats__descriptor,
                                allocator, len, data);
}
void   gatekeeper__hero_stats__hero_stats__free_unpacked
                     (Gatekeeper__HeroStats__HeroStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gatekeeper__hero_stats__hero_observation_window__init
                     (Gatekeeper__HeroStats__HeroObservationWindow         *message)
{
  static const Gatekeeper__HeroStats__HeroObservationWindow init_value = GATEKEEPER__HERO_STATS__HERO_OBSERVATION_WINDOW__INIT;
  *message = init_value;
}
size_t gatekeeper__hero_stats__hero_observation_window__get_packed_size
                     (const Gatekeeper__HeroStats__HeroObservationWindow *message)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_observation_window__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gatekeeper__hero_stats__hero_observation_window__pack
                     (const Gatekeeper__HeroStats__HeroObservationWindow *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_observation_window__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gatekeeper__hero_stats__hero_observation_window__pack_to_buffer
                     (const Gatekeeper__HeroStats__HeroObservationWindow *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_observation_window__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gatekeeper__HeroStats__HeroObservationWindow *
       gatekeeper__hero_stats__hero_observation_window__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gatekeeper__HeroStats__HeroObservationWindow *)
     protobuf_c_message_unpack (&gatekeeper__hero_stats__hero_observation_window__descriptor,
                                allocator, len, data);
}
void   gatekeeper__hero_stats__hero_observation_window__free_unpacked
                     (Gatekeeper__HeroStats__HeroObservationWindow *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_observation_window__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gatekeeper__hero_stats__hero_report__init
                     (Gatekeeper__HeroStats__HeroReport         *message)
{
  static const Gatekeeper__HeroStats__HeroReport init_value = GATEKEEPER__HERO_STATS__HERO_REPORT__INIT;
  *message = init_value;
}
size_t gatekeeper__hero_stats__hero_report__get_packed_size
                     (const Gatekeeper__HeroStats__HeroReport *message)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gatekeeper__hero_stats__hero_report__pack
                     (const Gatekeeper__HeroStats__HeroReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gatekeeper__hero_stats__hero_report__pack_to_buffer
                     (const Gatekeeper__HeroStats__HeroReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gatekeeper__HeroStats__HeroReport *
       gatekeeper__hero_stats__hero_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gatekeeper__HeroStats__HeroReport *)
     protobuf_c_message_unpack (&gatekeeper__hero_stats__hero_report__descriptor,
                                allocator, len, data);
}
void   gatekeeper__hero_stats__hero_report__free_unpacked
                     (Gatekeeper__HeroStats__HeroReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gatekeeper__hero_stats__hero_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor gatekeeper__hero_stats__hero_observation_point__field_descriptors[2] =
{
  {
    "node_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroObservationPoint, node_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroObservationPoint, location_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gatekeeper__hero_stats__hero_observation_point__field_indices_by_name[] = {
  1,   /* field[1] = location_id */
  0,   /* field[0] = node_id */
};
static const ProtobufCIntRange gatekeeper__hero_stats__hero_observation_point__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gatekeeper__hero_stats__hero_observation_point__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gatekeeper.hero_stats.HeroObservationPoint",
  "HeroObservationPoint",
  "Gatekeeper__HeroStats__HeroObservationPoint",
  "gatekeeper.hero_stats",
  sizeof(Gatekeeper__HeroStats__HeroObservationPoint),
  2,
  gatekeeper__hero_stats__hero_observation_point__field_descriptors,
  gatekeeper__hero_stats__hero_observation_point__field_indices_by_name,
  1,  gatekeeper__hero_stats__hero_observation_point__number_ranges,
  (ProtobufCMessageInit) gatekeeper__hero_stats__hero_observation_point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gatekeeper__hero_stats__hero_hostname__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroHostname, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count_fqdn",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroHostname, count_fqdn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count_host",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroHostname, count_host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count_sni",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroHostname, count_sni),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gatekeeper__hero_stats__hero_hostname__field_indices_by_name[] = {
  1,   /* field[1] = count_fqdn */
  2,   /* field[2] = count_host */
  3,   /* field[3] = count_sni */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange gatekeeper__hero_stats__hero_hostname__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor gatekeeper__hero_stats__hero_hostname__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gatekeeper.hero_stats.HeroHostname",
  "HeroHostname",
  "Gatekeeper__HeroStats__HeroHostname",
  "gatekeeper.hero_stats",
  sizeof(Gatekeeper__HeroStats__HeroHostname),
  4,
  gatekeeper__hero_stats__hero_hostname__field_descriptors,
  gatekeeper__hero_stats__hero_hostname__field_indices_by_name,
  1,  gatekeeper__hero_stats__hero_hostname__number_ranges,
  (ProtobufCMessageInit) gatekeeper__hero_stats__hero_hostname__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gatekeeper__hero_stats__hero_url__field_descriptors[2] =
{
  {
    "url",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroUrl, url),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroUrl, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gatekeeper__hero_stats__hero_url__field_indices_by_name[] = {
  1,   /* field[1] = count */
  0,   /* field[0] = url */
};
static const ProtobufCIntRange gatekeeper__hero_stats__hero_url__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gatekeeper__hero_stats__hero_url__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gatekeeper.hero_stats.HeroUrl",
  "HeroUrl",
  "Gatekeeper__HeroStats__HeroUrl",
  "gatekeeper.hero_stats",
  sizeof(Gatekeeper__HeroStats__HeroUrl),
  2,
  gatekeeper__hero_stats__hero_url__field_descriptors,
  gatekeeper__hero_stats__hero_url__field_indices_by_name,
  1,  gatekeeper__hero_stats__hero_url__number_ranges,
  (ProtobufCMessageInit) gatekeeper__hero_stats__hero_url__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gatekeeper__hero_stats__hero_ipv4__field_descriptors[2] =
{
  {
    "addr_ipv4",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroIpv4, addr_ipv4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroIpv4, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gatekeeper__hero_stats__hero_ipv4__field_indices_by_name[] = {
  0,   /* field[0] = addr_ipv4 */
  1,   /* field[1] = count */
};
static const ProtobufCIntRange gatekeeper__hero_stats__hero_ipv4__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gatekeeper__hero_stats__hero_ipv4__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gatekeeper.hero_stats.HeroIpv4",
  "HeroIpv4",
  "Gatekeeper__HeroStats__HeroIpv4",
  "gatekeeper.hero_stats",
  sizeof(Gatekeeper__HeroStats__HeroIpv4),
  2,
  gatekeeper__hero_stats__hero_ipv4__field_descriptors,
  gatekeeper__hero_stats__hero_ipv4__field_indices_by_name,
  1,  gatekeeper__hero_stats__hero_ipv4__number_ranges,
  (ProtobufCMessageInit) gatekeeper__hero_stats__hero_ipv4__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gatekeeper__hero_stats__hero_ipv6__field_descriptors[2] =
{
  {
    "addr_ipv6",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroIpv6, addr_ipv6),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroIpv6, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gatekeeper__hero_stats__hero_ipv6__field_indices_by_name[] = {
  0,   /* field[0] = addr_ipv6 */
  1,   /* field[1] = count */
};
static const ProtobufCIntRange gatekeeper__hero_stats__hero_ipv6__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gatekeeper__hero_stats__hero_ipv6__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gatekeeper.hero_stats.HeroIpv6",
  "HeroIpv6",
  "Gatekeeper__HeroStats__HeroIpv6",
  "gatekeeper.hero_stats",
  sizeof(Gatekeeper__HeroStats__HeroIpv6),
  2,
  gatekeeper__hero_stats__hero_ipv6__field_descriptors,
  gatekeeper__hero_stats__hero_ipv6__field_indices_by_name,
  1,  gatekeeper__hero_stats__hero_ipv6__number_ranges,
  (ProtobufCMessageInit) gatekeeper__hero_stats__hero_ipv6__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gatekeeper__hero_stats__hero_app__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroApp, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroApp, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gatekeeper__hero_stats__hero_app__field_indices_by_name[] = {
  1,   /* field[1] = count */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange gatekeeper__hero_stats__hero_app__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gatekeeper__hero_stats__hero_app__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gatekeeper.hero_stats.HeroApp",
  "HeroApp",
  "Gatekeeper__HeroStats__HeroApp",
  "gatekeeper.hero_stats",
  sizeof(Gatekeeper__HeroStats__HeroApp),
  2,
  gatekeeper__hero_stats__hero_app__field_descriptors,
  gatekeeper__hero_stats__hero_app__field_indices_by_name,
  1,  gatekeeper__hero_stats__hero_app__number_ranges,
  (ProtobufCMessageInit) gatekeeper__hero_stats__hero_app__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gatekeeper__hero_stats__hero_ipv4_flow_tuple__field_descriptors[6] =
{
  {
    "source_ipv4",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroIpv4FlowTuple, source_ipv4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "destination_ipv4",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroIpv4FlowTuple, destination_ipv4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transport",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroIpv4FlowTuple, transport),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source_port",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroIpv4FlowTuple, source_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "destination_port",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroIpv4FlowTuple, destination_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroIpv4FlowTuple, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gatekeeper__hero_stats__hero_ipv4_flow_tuple__field_indices_by_name[] = {
  5,   /* field[5] = count */
  1,   /* field[1] = destination_ipv4 */
  4,   /* field[4] = destination_port */
  0,   /* field[0] = source_ipv4 */
  3,   /* field[3] = source_port */
  2,   /* field[2] = transport */
};
static const ProtobufCIntRange gatekeeper__hero_stats__hero_ipv4_flow_tuple__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor gatekeeper__hero_stats__hero_ipv4_flow_tuple__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gatekeeper.hero_stats.HeroIpv4FlowTuple",
  "HeroIpv4FlowTuple",
  "Gatekeeper__HeroStats__HeroIpv4FlowTuple",
  "gatekeeper.hero_stats",
  sizeof(Gatekeeper__HeroStats__HeroIpv4FlowTuple),
  6,
  gatekeeper__hero_stats__hero_ipv4_flow_tuple__field_descriptors,
  gatekeeper__hero_stats__hero_ipv4_flow_tuple__field_indices_by_name,
  1,  gatekeeper__hero_stats__hero_ipv4_flow_tuple__number_ranges,
  (ProtobufCMessageInit) gatekeeper__hero_stats__hero_ipv4_flow_tuple__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gatekeeper__hero_stats__hero_ipv6_flow_tuple__field_descriptors[6] =
{
  {
    "source_ipv6",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroIpv6FlowTuple, source_ipv6),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "destination_ipv6",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroIpv6FlowTuple, destination_ipv6),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transport",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroIpv6FlowTuple, transport),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source_port",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroIpv6FlowTuple, source_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "destination_port",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroIpv6FlowTuple, destination_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroIpv6FlowTuple, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gatekeeper__hero_stats__hero_ipv6_flow_tuple__field_indices_by_name[] = {
  5,   /* field[5] = count */
  1,   /* field[1] = destination_ipv6 */
  4,   /* field[4] = destination_port */
  0,   /* field[0] = source_ipv6 */
  3,   /* field[3] = source_port */
  2,   /* field[2] = transport */
};
static const ProtobufCIntRange gatekeeper__hero_stats__hero_ipv6_flow_tuple__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor gatekeeper__hero_stats__hero_ipv6_flow_tuple__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gatekeeper.hero_stats.HeroIpv6FlowTuple",
  "HeroIpv6FlowTuple",
  "Gatekeeper__HeroStats__HeroIpv6FlowTuple",
  "gatekeeper.hero_stats",
  sizeof(Gatekeeper__HeroStats__HeroIpv6FlowTuple),
  6,
  gatekeeper__hero_stats__hero_ipv6_flow_tuple__field_descriptors,
  gatekeeper__hero_stats__hero_ipv6_flow_tuple__field_indices_by_name,
  1,  gatekeeper__hero_stats__hero_ipv6_flow_tuple__number_ranges,
  (ProtobufCMessageInit) gatekeeper__hero_stats__hero_ipv6_flow_tuple__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gatekeeper__hero_stats__hero_stats__field_descriptors[13] =
{
  {
    "device_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroStats, device_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroStats, action),
    &gatekeeper__hero_stats__hero_actions__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "category_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroStats, category_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "policy",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroStats, policy),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_access_ts",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroStats, last_access_ts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroStats, direction),
    &gatekeeper__hero_stats__hero_directions__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostname",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroStats, hostname),
    &gatekeeper__hero_stats__hero_hostname__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "url",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroStats, url),
    &gatekeeper__hero_stats__hero_url__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroStats, ipv4),
    &gatekeeper__hero_stats__hero_ipv4__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroStats, ipv6),
    &gatekeeper__hero_stats__hero_ipv6__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroStats, app),
    &gatekeeper__hero_stats__hero_app__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_tuple",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroStats, ipv4_tuple),
    &gatekeeper__hero_stats__hero_ipv4_flow_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_tuple",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroStats, ipv6_tuple),
    &gatekeeper__hero_stats__hero_ipv6_flow_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gatekeeper__hero_stats__hero_stats__field_indices_by_name[] = {
  1,   /* field[1] = action */
  10,   /* field[10] = app */
  2,   /* field[2] = category_id */
  0,   /* field[0] = device_id */
  5,   /* field[5] = direction */
  6,   /* field[6] = hostname */
  8,   /* field[8] = ipv4 */
  11,   /* field[11] = ipv4_tuple */
  9,   /* field[9] = ipv6 */
  12,   /* field[12] = ipv6_tuple */
  4,   /* field[4] = last_access_ts */
  3,   /* field[3] = policy */
  7,   /* field[7] = url */
};
static const ProtobufCIntRange gatekeeper__hero_stats__hero_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor gatekeeper__hero_stats__hero_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gatekeeper.hero_stats.HeroStats",
  "HeroStats",
  "Gatekeeper__HeroStats__HeroStats",
  "gatekeeper.hero_stats",
  sizeof(Gatekeeper__HeroStats__HeroStats),
  13,
  gatekeeper__hero_stats__hero_stats__field_descriptors,
  gatekeeper__hero_stats__hero_stats__field_indices_by_name,
  1,  gatekeeper__hero_stats__hero_stats__number_ranges,
  (ProtobufCMessageInit) gatekeeper__hero_stats__hero_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gatekeeper__hero_stats__hero_observation_window__field_descriptors[3] =
{
  {
    "started_at",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroObservationWindow, started_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ended_at",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroObservationWindow, ended_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hero_stats",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gatekeeper__HeroStats__HeroObservationWindow, n_hero_stats),
    offsetof(Gatekeeper__HeroStats__HeroObservationWindow, hero_stats),
    &gatekeeper__hero_stats__hero_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gatekeeper__hero_stats__hero_observation_window__field_indices_by_name[] = {
  1,   /* field[1] = ended_at */
  2,   /* field[2] = hero_stats */
  0,   /* field[0] = started_at */
};
static const ProtobufCIntRange gatekeeper__hero_stats__hero_observation_window__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor gatekeeper__hero_stats__hero_observation_window__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gatekeeper.hero_stats.HeroObservationWindow",
  "HeroObservationWindow",
  "Gatekeeper__HeroStats__HeroObservationWindow",
  "gatekeeper.hero_stats",
  sizeof(Gatekeeper__HeroStats__HeroObservationWindow),
  3,
  gatekeeper__hero_stats__hero_observation_window__field_descriptors,
  gatekeeper__hero_stats__hero_observation_window__field_indices_by_name,
  1,  gatekeeper__hero_stats__hero_observation_window__number_ranges,
  (ProtobufCMessageInit) gatekeeper__hero_stats__hero_observation_window__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gatekeeper__hero_stats__hero_report__field_descriptors[3] =
{
  {
    "reported_at",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroReport, reported_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "observation_point",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gatekeeper__HeroStats__HeroReport, observation_point),
    &gatekeeper__hero_stats__hero_observation_point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "observation_window",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gatekeeper__HeroStats__HeroReport, n_observation_window),
    offsetof(Gatekeeper__HeroStats__HeroReport, observation_window),
    &gatekeeper__hero_stats__hero_observation_window__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gatekeeper__hero_stats__hero_report__field_indices_by_name[] = {
  1,   /* field[1] = observation_point */
  2,   /* field[2] = observation_window */
  0,   /* field[0] = reported_at */
};
static const ProtobufCIntRange gatekeeper__hero_stats__hero_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor gatekeeper__hero_stats__hero_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gatekeeper.hero_stats.HeroReport",
  "HeroReport",
  "Gatekeeper__HeroStats__HeroReport",
  "gatekeeper.hero_stats",
  sizeof(Gatekeeper__HeroStats__HeroReport),
  3,
  gatekeeper__hero_stats__hero_report__field_descriptors,
  gatekeeper__hero_stats__hero_report__field_indices_by_name,
  1,  gatekeeper__hero_stats__hero_report__number_ranges,
  (ProtobufCMessageInit) gatekeeper__hero_stats__hero_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue gatekeeper__hero_stats__hero_actions__enum_values_by_number[3] =
{
  { "HERO_ACTION_UNSPECIFIED", "GATEKEEPER__HERO_STATS__HERO_ACTIONS__HERO_ACTION_UNSPECIFIED", 0 },
  { "HERO_ACTION_ALLOW", "GATEKEEPER__HERO_STATS__HERO_ACTIONS__HERO_ACTION_ALLOW", 1 },
  { "HERO_ACTION_BLOCK", "GATEKEEPER__HERO_STATS__HERO_ACTIONS__HERO_ACTION_BLOCK", 2 },
};
static const ProtobufCIntRange gatekeeper__hero_stats__hero_actions__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex gatekeeper__hero_stats__hero_actions__enum_values_by_name[3] =
{
  { "HERO_ACTION_ALLOW", 1 },
  { "HERO_ACTION_BLOCK", 2 },
  { "HERO_ACTION_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor gatekeeper__hero_stats__hero_actions__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "gatekeeper.hero_stats.HeroActions",
  "HeroActions",
  "Gatekeeper__HeroStats__HeroActions",
  "gatekeeper.hero_stats",
  3,
  gatekeeper__hero_stats__hero_actions__enum_values_by_number,
  3,
  gatekeeper__hero_stats__hero_actions__enum_values_by_name,
  1,
  gatekeeper__hero_stats__hero_actions__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue gatekeeper__hero_stats__hero_directions__enum_values_by_number[4] =
{
  { "HERO_DIR_UNSET", "GATEKEEPER__HERO_STATS__HERO_DIRECTIONS__HERO_DIR_UNSET", 0 },
  { "HERO_DIR_INBOUND", "GATEKEEPER__HERO_STATS__HERO_DIRECTIONS__HERO_DIR_INBOUND", 1 },
  { "HERO_DIR_OUTBOUND", "GATEKEEPER__HERO_STATS__HERO_DIRECTIONS__HERO_DIR_OUTBOUND", 2 },
  { "HERO_DIR_LAN2LAN", "GATEKEEPER__HERO_STATS__HERO_DIRECTIONS__HERO_DIR_LAN2LAN", 3 },
};
static const ProtobufCIntRange gatekeeper__hero_stats__hero_directions__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex gatekeeper__hero_stats__hero_directions__enum_values_by_name[4] =
{
  { "HERO_DIR_INBOUND", 1 },
  { "HERO_DIR_LAN2LAN", 3 },
  { "HERO_DIR_OUTBOUND", 2 },
  { "HERO_DIR_UNSET", 0 },
};
const ProtobufCEnumDescriptor gatekeeper__hero_stats__hero_directions__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "gatekeeper.hero_stats.HeroDirections",
  "HeroDirections",
  "Gatekeeper__HeroStats__HeroDirections",
  "gatekeeper.hero_stats",
  4,
  gatekeeper__hero_stats__hero_directions__enum_values_by_number,
  4,
  gatekeeper__hero_stats__hero_directions__enum_values_by_name,
  1,
  gatekeeper__hero_stats__hero_directions__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
